-- Yamansa Rulman B2B — shared cloud schema (Supabase / Postgres).
-- Idempotent: safe to re-run. Applied with the Supabase Management API (see README "Bulut").

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- tables
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  contact text not null default '',
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  city text not null default '',
  tax_no text not null default '',
  tax_office text not null default '',
  discount_pct numeric not null default 0,
  currency text not null default 'TRY',
  notes text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  display_name text not null default '',
  role text not null default 'bayi' check (role in ('admin', 'bayi')),
  customer_id bigint references public.customers(id) on delete set null,
  active boolean not null default true,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists profiles_username_lower on public.profiles (lower(username));

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text not null,
  sku_norm text not null unique,
  name text not null default '',
  name_norm text not null default '',
  brand text not null default '',
  category text not null default '',
  type text not null default '',
  seal text not null default '',
  d_inner numeric, d_outer numeric, width numeric,
  stock numeric not null default 0,
  unit text not null default 'Adet',
  price numeric not null default 0,
  currency text not null default 'TRY',
  list_price numeric,
  card_price numeric,
  min_order numeric not null default 1,
  shelf text not null default '',
  barcode text not null default '',
  image text not null default '',
  description text not null default '',
  equivalents text not null default '',
  active boolean not null default true,
  deleted boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists products_updated_at on public.products (updated_at, id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null default '',
  status text not null default 'beklemede',
  note text not null default '',
  payment text not null default 'pesin',
  currency text not null default 'TRY',
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  vat_pct numeric not null default 20,
  vat numeric not null default 0,
  total numeric not null default 0,
  created_by text not null default '',
  created_by_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_customer on public.orders (customer_id);
create index if not exists orders_created on public.orders (created_at desc);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  sku text not null,
  name text not null default '',
  qty numeric not null,
  unit_price numeric not null,
  discount_pct numeric not null default 0,
  line_total numeric not null
);
create index if not exists order_items_order on public.order_items (order_id);

create table if not exists public.settings (key text primary key, value jsonb not null);

create table if not exists public.import_logs (
  id bigint generated by default as identity primary key,
  filename text not null,
  created_at timestamptz not null default now(),
  inserted integer not null default 0,
  updated integer not null default 0,
  unchanged integer not null default 0,
  deactivated integer not null default 0,
  mode text not null default 'upsert'
);

-- ---------------------------------------------------------------- helpers
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and role = 'admin' and active and approved)
$$;

create or replace function public.is_member() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and active and approved)
$$;

create or replace function public.my_customer_id() returns bigint
language sql stable security definer set search_path = public as $$
  select customer_id from profiles where id = auth.uid() and active and approved
$$;

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at();

create or replace function public.next_customer_code() returns text
language plpgsql security definer set search_path = public as $$
declare n int; v_code text;
begin
  select count(*) + 1 into n from customers;
  v_code := 'B' || lpad(n::text, 4, '0');
  while exists (select 1 from customers c where c.code = v_code) loop
    n := n + 1;
    v_code := 'B' || lpad(n::text, 4, '0');
  end loop;
  return v_code;
end $$;

-- Every sign-up becomes a dealer with its own company card, locked until an administrator approves it.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare uname text; dname text; cid bigint; is_first boolean;
begin
  uname := coalesce(nullif(trim(new.raw_user_meta_data->>'username'), ''), split_part(new.email, '@', 1));
  dname := coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), uname);
  is_first := not exists (select 1 from profiles);
  insert into customers (code, name) values (next_customer_code(), dname) returning id into cid;
  insert into profiles (id, username, display_name, role, customer_id, approved)
  values (new.id, uname, dname, case when is_first then 'admin' else 'bayi' end, cid, is_first);
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------- RPC (security definer, role checks inside)
create or replace function public.update_my_company(p jsonb) returns customers
language plpgsql security definer set search_path = public as $$
declare cid bigint := my_customer_id(); c customers;
begin
  if cid is null then raise exception 'Bu hesaba bağlı bir cari kart yok.'; end if;
  if coalesce(trim(p->>'name'), '') = '' then raise exception 'Firma / ünvan boş olamaz.'; end if;
  if coalesce(p->>'tax_no', '') <> '' and trim(p->>'tax_no') !~ '^\d{10,11}$' then
    raise exception 'Vergi no 10 haneli (VKN) veya TC kimlik no 11 haneli olmalı.';
  end if;
  update customers set
    name = trim(p->>'name'), contact = coalesce(trim(p->>'contact'), ''), phone = coalesce(trim(p->>'phone'), ''),
    email = coalesce(trim(p->>'email'), ''), address = coalesce(trim(p->>'address'), ''), city = coalesce(trim(p->>'city'), ''),
    tax_no = coalesce(trim(p->>'tax_no'), ''), tax_office = coalesce(trim(p->>'tax_office'), '')
  where id = cid returning * into c;
  return c;
end $$;

create or replace function public.adjust_stock(p_id bigint, p_delta numeric) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then raise exception 'Bu işlem için yetkiniz yok.'; end if;
  update products set stock = greatest(0, stock + p_delta) where id = p_id;
end $$;

create or replace function public.create_order(p_customer_id bigint, p_note text, p_payment text, p_currency text, p_vat_pct numeric, p_items jsonb)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  me profiles; cid bigint; cname text; oid bigint; ono text; seq int; prefix text;
  it jsonb; gross numeric := 0; sub numeric := 0; lt numeric; q numeric; up numeric; dp numeric; pid bigint;
begin
  select * into me from profiles where id = auth.uid() and active and approved;
  if me.id is null then raise exception 'Oturum açılmamış.'; end if;
  cid := case when me.role = 'admin' then p_customer_id else me.customer_id end;
  if cid is null then raise exception 'Lütfen bir bayi/müşteri seçin.'; end if;
  select name into cname from customers where id = cid;
  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then raise exception 'Sipariş en az bir kalem içermeli.'; end if;

  perform pg_advisory_xact_lock(hashtext('order_no'));
  prefix := 'SP-' || to_char(now() at time zone 'Europe/Istanbul', 'YYYYMMDD') || '-';
  select coalesce(max(substr(order_no, length(prefix) + 1)::int), 0) + 1 into seq from orders where order_no like prefix || '%';
  ono := prefix || lpad(seq::text, 3, '0');

  for it in select * from jsonb_array_elements(p_items) loop
    q := coalesce((it->>'qty')::numeric, 0);
    if q <= 0 then continue; end if;
    up := coalesce((it->>'unit_price')::numeric, 0);
    dp := coalesce((it->>'discount_pct')::numeric, 0);
    gross := gross + q * up;
    sub := sub + round(q * up * (1 - dp / 100), 2);
  end loop;
  if sub = 0 and gross = 0 then raise exception 'Sipariş en az bir kalem içermeli.'; end if;

  insert into orders (order_no, customer_id, customer_name, status, note, payment, currency, subtotal, discount, vat_pct, vat, total, created_by, created_by_id)
  values (ono, cid, coalesce(cname, ''), 'beklemede', coalesce(p_note, ''), case when p_payment = 'kart' then 'kart' else 'pesin' end,
          coalesce(p_currency, 'TRY'), round(sub, 2), round(gross - sub, 2), p_vat_pct, round(sub * p_vat_pct / 100, 2),
          round(sub + round(sub * p_vat_pct / 100, 2), 2), coalesce(nullif(me.display_name, ''), me.username), me.id)
  returning id into oid;

  for it in select * from jsonb_array_elements(p_items) loop
    q := coalesce((it->>'qty')::numeric, 0);
    if q <= 0 then continue; end if;
    up := coalesce((it->>'unit_price')::numeric, 0);
    dp := coalesce((it->>'discount_pct')::numeric, 0);
    lt := round(q * up * (1 - dp / 100), 2);
    pid := nullif(it->>'product_id', '')::bigint;
    insert into order_items (order_id, product_id, sku, name, qty, unit_price, discount_pct, line_total)
    values (oid, pid, coalesce(it->>'sku', ''), coalesce(it->>'name', ''), q, up, dp, lt);
    if pid is not null then update products set stock = greatest(0, stock - q) where id = pid; end if;
  end loop;
  return oid;
end $$;

create or replace function public.set_order_status(p_id bigint, p_status text) returns void
language plpgsql security definer set search_path = public as $$
declare o orders; it order_items;
begin
  select * into o from orders where id = p_id;
  if o.id is null then raise exception 'Sipariş bulunamadı.'; end if;
  if not is_admin() then
    if p_status <> 'iptal' or o.customer_id is distinct from my_customer_id() then
      raise exception 'Sipariş durumunu yalnızca yöneticiler değiştirebilir.';
    end if;
  end if;
  if p_status = 'iptal' and o.status <> 'iptal' then
    for it in select * from order_items where order_id = p_id and product_id is not null loop
      update products set stock = stock + it.qty where id = it.product_id;
    end loop;
  elsif o.status = 'iptal' and p_status <> 'iptal' then
    for it in select * from order_items where order_id = p_id and product_id is not null loop
      update products set stock = greatest(0, stock - it.qty) where id = it.product_id;
    end loop;
  end if;
  update orders set status = p_status, updated_at = now() where id = p_id;
end $$;

create or replace function public.admin_set_password(p_user uuid, p_password text) returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  if not is_admin() then raise exception 'Bu işlem için yetkiniz yok.'; end if;
  if length(p_password) < 6 then raise exception 'Şifre en az 6 karakter olmalı.'; end if;
  update auth.users set encrypted_password = crypt(p_password, gen_salt('bf')), updated_at = now() where id = p_user;
end $$;

create or replace function public.admin_delete_user(p_user uuid) returns void
language plpgsql security definer set search_path = public as $$
declare t profiles;
begin
  if not is_admin() then raise exception 'Bu işlem için yetkiniz yok.'; end if;
  select * into t from profiles where id = p_user;
  if t.role = 'admin' and not exists (select 1 from profiles where role = 'admin' and active and id <> p_user) then
    raise exception 'Son yönetici silinemez.';
  end if;
  delete from auth.users where id = p_user;
  if t.customer_id is not null then
    delete from customers c where c.id = t.customer_id
      and not exists (select 1 from orders where customer_id = c.id)
      and not exists (select 1 from profiles where customer_id = c.id)
      and c.tax_no = '' and c.phone = '' and c.address = '';
  end if;
end $$;

create or replace function public.deactivate_products_not_in(p_norms text[]) returns integer
language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if not is_admin() then raise exception 'Bu işlem için yetkiniz yok.'; end if;
  update products set active = false where active and not deleted and not (sku_norm = any (p_norms));
  get diagnostics n = row_count;
  return n;
end $$;

create or replace function public.soft_delete_all_products() returns void
language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then raise exception 'Bu işlem için yetkiniz yok.'; end if;
  update products set deleted = true, active = false where not deleted;
end $$;

create or replace function public.dashboard_orders(p_customer bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare cid bigint; res jsonb;
begin
  if not is_member() then raise exception 'Oturum açılmamış.'; end if;
  cid := case when is_admin() then p_customer else my_customer_id() end;
  select jsonb_build_object(
    'openOrders', (select count(*) from orders where status in ('beklemede','onaylandi','hazirlaniyor') and (cid is null or customer_id = cid)),
    'ordersToday', (select count(*) from orders where (created_at at time zone 'Europe/Istanbul')::date = (now() at time zone 'Europe/Istanbul')::date and (cid is null or customer_id = cid)),
    'customerCount', (select count(*) from customers where active),
    'pendingUsers', case when is_admin() then (select count(*) from profiles where not approved) else 0 end,
    'recentOrders', coalesce((select jsonb_agg(to_jsonb(o)) from (select * from orders where cid is null or customer_id = cid order by created_at desc, id desc limit 8) o), '[]'::jsonb),
    'lastImport', (select to_jsonb(l) from import_logs l order by id desc limit 1)
  ) into res;
  return res;
end $$;

-- ---------------------------------------------------------------- RLS
alter table public.customers enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.settings enable row level security;
alter table public.import_logs enable row level security;

drop policy if exists customers_select on public.customers;
create policy customers_select on public.customers for select to authenticated using (is_admin() or id = my_customer_id());
drop policy if exists customers_admin on public.customers;
create policy customers_admin on public.customers for all to authenticated using (is_admin()) with check (is_admin());

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (is_admin() or id = auth.uid());
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using (is_admin()) with check (is_admin());

drop policy if exists products_select on public.products;
create policy products_select on public.products for select to authenticated using (is_member());
drop policy if exists products_admin on public.products;
create policy products_admin on public.products for all to authenticated using (is_admin()) with check (is_admin());

drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders for select to authenticated using (is_admin() or customer_id = my_customer_id());
drop policy if exists orders_admin on public.orders;
create policy orders_admin on public.orders for all to authenticated using (is_admin()) with check (is_admin());
drop policy if exists order_items_select on public.order_items;
create policy order_items_select on public.order_items for select to authenticated
  using (exists (select 1 from orders o where o.id = order_id and (is_admin() or o.customer_id = my_customer_id())));

drop policy if exists order_items_admin on public.order_items;
create policy order_items_admin on public.order_items for all to authenticated using (is_admin()) with check (is_admin());

drop policy if exists settings_select on public.settings;
create policy settings_select on public.settings for select to authenticated using (is_member());
drop policy if exists settings_admin on public.settings;
create policy settings_admin on public.settings for all to authenticated using (is_admin()) with check (is_admin());

drop policy if exists import_logs_admin on public.import_logs;
create policy import_logs_admin on public.import_logs for all to authenticated using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------- realtime
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'products') then
    alter publication supabase_realtime add table public.products;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'profiles') then
    alter publication supabase_realtime add table public.profiles;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'customers') then
    alter publication supabase_realtime add table public.customers;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'settings') then
    alter publication supabase_realtime add table public.settings;
  end if;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
revoke execute on function public.handle_new_user() from authenticated, anon;
