# -*- coding: utf-8 -*-
"""Yamansa Rulman – 30 günlük içerik planının tek kaynağı.

Hem takvim dosyaları (MD/CSV) hem de görseller bu listeden üretilir.
"""

SITE = "https://www.yamansarulman.com"
TEL = "0212 670 02 05"
ADRES = "İkitelli OSB, Heskop San. Sit. M4 Blok No:47, Başakşehir / İstanbul"

# Ortak hashtag setleri (Instagram/Facebook için). LinkedIn'de en fazla 3-5 tanesi kullanılır.
HASHTAG_SETS = {
    "genel": "#rulman #yamansarulman #rulmanfiyatları #sanayi #yedekparça #istanbul #ikitelli",
    "moto": "#motosiklet #motosikletyedekparça #tekerlekrulmanı #motorrulmanı #honda #yamaha #bajaj #ktm #cfmoto #mondial",
    "scooter": "#elektrikliscooter #scooter #xiaomi #segway #ninebot #dualtron #navee #scooteryedekparça",
    "teknik": "#rulmanteknik #makinebakım #bakımonarım #mühendislik #tekniker",
    "bisiklet": "#bisiklet #salcano #bisikletyedekparça #bisiklettamir",
    "sanayi": "#endüstri #makineimalat #fabrika #bakım #konikrulman #silindirikrulman",
}

# Her kayıt: görsel şablonu + platform metinleri + SEO alanları
POSTS = [
    dict(
        gun=1, tarih="21 Eyl 2026 Pzt", platform="IG, FB, LI", pillar="Marka",
        sablon="hero", foto="19911427.jpg", etiket="1986'DAN BERİ",
        baslik="RULMANDA<br>DOĞRU ADRES.",
        alt="Sabit bilyalı, konik, silindirik ve oynak rulmanlar – orijinal, faturalı, stoktan aynı gün kargo.",
        kw="rulman, rulman tedarikçisi İstanbul, rulman satış",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=lansman",
        alt_text="Yamansa Rulman açılış gönderisi: çelik bilyalı rulman fotoğrafı üzerinde 'Rulmanda doğru adres' başlığı",
        ig="Yamansa Rulman artık sosyal medyada! 1986'dan beri İkitelli OSB'den tüm Türkiye'ye rulman tedarik ediyoruz.\n\n• SKF, FAG, ORS, NMB, TPI ve Yamansa markalı setler\n• Motosiklet, scooter, bisiklet ve sanayi rulmanları\n• Stoktan aynı gün kargo, faturalı ve orijinal ürün\n\nÖlçünüzü yazın, doğru rulmanı bulalım. Katalog: yamansarulman.com",
        li="Yamansa Rulman olarak 1986'dan bu yana rulman ithalatı ve distribütörlüğü yapıyoruz. Bu sayfada sektör bilgisi, ürün serileri ve tedarik süreçlerimizi paylaşacağız.\n\nOdak alanlarımız: sabit bilyalı rulmanlar (ZZ/2RS), motosiklet ve e-scooter tekerlek rulmanları, sanayi tipi konik ve silindirik makaralı rulmanlar. Distribütörlüğünü yürüttüğümüz markalar: SKF, FAG, ORS, NMB, TPI.\n\nBayi ve toplu alım talepleri için: yamansarulman.com",
        hashtags="genel", blog="Yamansa Rulman hakkında: 1986'dan bugüne (Hakkımızda sayfası SEO metni)",
    ),
    dict(
        gun=2, tarih="22 Eyl 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6200",
        baslik="6200 SERİSİ<br>SABİT BİLYALI",
        alt="En çok aranan ölçüler stokta. ZZ (metal kapak) ve 2RS (kauçuk keçe) seçenekleri.",
        tablo=[("6200", "10 × 30 × 9"), ("6201", "12 × 32 × 10"), ("6202", "15 × 35 × 11"),
               ("6203", "17 × 40 × 12"), ("6204", "20 × 47 × 14"), ("6205", "25 × 52 × 15")],
        kw="6204 rulman, 6203 rulman, 6200 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6200",
        alt_text="6200 serisi rulman ölçü tablosu: 6200'den 6205'e iç çap, dış çap ve kalınlık",
        ig="6200 serisi, sanayide ve motosiklette en çok kullanılan sabit bilyalı rulman ailesi.\n\n6200 → 10×30×9\n6201 → 12×32×10\n6202 → 15×35×11\n6203 → 17×40×12\n6204 → 20×47×14\n6205 → 25×52×15\n\nZZ mi 2RS mi? Yarın anlatıyoruz. Fiyat ve stok için DM veya yamansarulman.com",
        hashtags="genel", blog="6200 serisi rulman ölçüleri ve kullanım alanları (ölçü tablosu sayfası)",
    ),
    dict(
        gun=3, tarih="23 Eyl 2026 Çar", platform="IG, FB, LI", pillar="Teknik",
        sablon="karsilastirma", foto="35568191.jpg", etiket="TEKNİK BİLGİ",
        baslik="ZZ Mİ,<br>2RS Mİ?",
        alt="Kapak tipi seçimi rulman ömrünü belirler.",
        sol=("ZZ", "Metal kapak", ["Yüksek devir", "Düşük sürtünme", "Toz koruması", "Kuru ortam"]),
        sag=("2RS", "Kauçuk keçe", ["Su & çamur koruması", "Gres içinde kalır", "Tekerlek / dış ortam", "Orta devir"]),
        kw="zz rulman 2rs rulman farkı, kapaklı rulman keçeli rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=zz-2rs",
        alt_text="ZZ metal kapaklı ve 2RS kauçuk keçeli rulman karşılaştırma grafiği",
        ig="ZZ mi 2RS mi? En çok aldığımız soru.\n\nZZ (metal kapak): yüksek devir, düşük sürtünme, kuru ve temiz ortam. Elektrik motoru, fan, spindle.\n\n2RS (kauçuk keçe): su, çamur ve toza karşı tam koruma; gres içinde kalır. Motosiklet ve scooter tekerlekleri, dış ortam.\n\nKural: Tekerlekse 2RS, motorsa ZZ. Emin değilseniz ölçüyü yazın, birlikte seçelim.",
        li="Rulman seçiminde kapak tipi çoğu zaman ihmal edilir; oysa arızaların önemli bir kısmı yanlış kapak seçiminden kaynaklanır.\n\nZZ (metal kapak): düşük sürtünme ve yüksek devir; toz koruması sağlar, sıvıya karşı korumaz. Elektrik motorları ve fanlar için idealdir.\n\n2RS (kauçuk keçe): su ve çamura karşı temas eden sızdırmazlık; gres rulman içinde kalır. Tekerlek, dış ortam ve yıkamaya maruz uygulamalar için tercih edilir.\n\nDoğru seçim, doğru ömür. Teknik danışmanlık için ekibimizle iletişime geçebilirsiniz.",
        hashtags="teknik", blog="ZZ ve 2RS rulman farkı nedir? Hangi uygulamada hangisi kullanılır?",
    ),
    dict(
        gun=4, tarih="24 Eyl 2026 Per", platform="IG, FB, LI", pillar="Uygulama",
        sablon="split", foto="18171624.jpg", etiket="MOTOSİKLET",
        baslik="TEKERLEK<br>RULMANI<br>SETLERİ",
        alt="Honda, Yamaha, Bajaj, KTM, CFMOTO, Mondial, RKS, Kuba, Suzuki ve daha fazlası için ön/arka tekerlek rulman setleri.",
        kw="motosiklet tekerlek rulmanı, honda tekerlek rulmanı, bajaj rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=moto-tekerlek",
        alt_text="Motosiklet ön tekerlek ve fren diski fotoğrafı; Yamansa motosiklet tekerlek rulmanı setleri",
        ig="Tekerlekten uğultu mu geliyor? Direksiyonda titreşim mi var? Büyük ihtimalle tekerlek rulmanı.\n\nHonda, Yamaha, Bajaj, KTM, CFMOTO, Mondial, RKS, Kuba, Suzuki, TVS, Yuki, Arora, Falcon… 26 marka için ön ve arka tekerlek rulman setlerimiz hazır.\n\nModelinizi yazın, doğru seti aynı gün kargolayalım.",
        li="Motosiklet servisleri için en sık değişen parçalardan biri tekerlek rulmanı. Yanlış ölçü ya da düşük kaliteli rulman, birkaç ay içinde aynı arızayı tekrarlatır.\n\nYamansa olarak 26 motosiklet markası için model bazlı ön/arka tekerlek rulman setleri hazırladık; SKF, FAG, ORS veya Yamansa markalı alternatiflerle. Servisler ve yedek parça bayileri için toplu fiyatlandırma mevcuttur.",
        hashtags="moto", blog="Motosiklet tekerlek rulmanı nasıl anlaşılır, nasıl değişir? Marka-model ölçü rehberi",
    ),
    dict(
        gun=5, tarih="25 Eyl 2026 Cum", platform="IG, FB", pillar="Marka",
        sablon="markalar", foto="7565159.jpg", etiket="DİSTRİBÜTÖR",
        baslik="ORİJİNAL.<br>FATURALI.<br>STOKTAN.",
        alt="Distribütörlüğünü yürüttüğümüz ve stoklarımızda bulunan markalar.",
        markalar=["SKF", "FAG", "ORS", "NMB", "TPI", "YAMANSA"],
        kw="skf rulman, fag rulman, ors rulman, orijinal rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=markalar",
        alt_text="SKF, FAG, ORS, NMB, TPI ve Yamansa marka logotipleri; orijinal faturalı rulman",
        ig="Piyasada sahte rulman var, biliyoruz. Bizde yok.\n\nSKF • FAG • ORS • NMB • TPI • Yamansa\n\nHer ürün orijinal, faturalı ve stoktan. 1986'dan beri aynı adreste, aynı ilkeyle.\n\nMarka tercihini yaz, fiyatı gönderelim.",
        hashtags="genel", blog="Sahte rulman nasıl anlaşılır? Orijinal SKF/FAG rulman kontrol rehberi",
    ),
    dict(
        gun=6, tarih="26 Eyl 2026 Cmt", platform="IG, FB", pillar="Teknik",
        sablon="kod", foto="20607184.jpg", etiket="NASIL OKUNUR?",
        baslik="RULMAN KODU<br>NASIL OKUNUR?",
        alt="Örnek: 6204-2RS C3",
        kod=[("62", "Seri (sabit bilyalı, orta)"), ("04", "İç çap: 04 × 5 = 20 mm"),
             ("2RS", "İki taraf kauçuk keçe"), ("C3", "Normalden geniş boşluk")],
        kw="rulman kodu okuma, rulman numarası ne anlama gelir, 6204 2rs c3",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=rulman-kodu",
        alt_text="6204-2RS C3 rulman kodunun parçalara ayrılmış açıklaması",
        ig="6204-2RS C3 ne demek?\n\n62 → Seri (sabit bilyalı, orta yük)\n04 → İç çap kodu: 04×5 = 20 mm\n2RS → İki tarafı kauçuk keçeli\nC3 → Normalden geniş iç boşluk (ısınan uygulamalar)\n\nNot: 00=10, 01=12, 02=15, 03=17 mm; 04'ten sonrası ×5.\n\nKaydet, lazım olur. Sorularınızı yoruma yazın.",
        hashtags="teknik", blog="Rulman kodları nasıl okunur? Tam rehber (ek harfler, boşluk sınıfları)",
    ),
    dict(
        gun=7, tarih="27 Eyl 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="35568191.jpg", etiket="PAZAR NOTU",
        baslik="“Bir makinenin sesi,<br>rulmanının sağlığıdır.”",
        alt="İyi bir rulman kendini duyurmaz; yalnızca çalışır.",
        kw="rulman bakımı, rulman sesi",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar",
        alt_text="Makro çekim bilyalı rulman fotoğrafı üzerine alıntı: Bir makinenin sesi, rulmanının sağlığıdır",
        ig="Bir makinenin sesi, rulmanının sağlığıdır.\n\nİyi haftalar. Pazartesi e-scooter rulmanlarıyla devam ediyoruz.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=8, tarih="28 Eyl 2026 Pzt", platform="IG, FB, LI", pillar="Uygulama",
        sablon="split", foto="38292508.jpg", etiket="E-SCOOTER",
        baslik="SCOOTER<br>RULMANLARI<br>STOKTA",
        alt="Xiaomi, Segway Ninebot, Dualtron, Navee, Citymate, Onvo, Hoofer, Volta için tekerlek ve motor rulmanları.",
        kw="scooter rulmanı, xiaomi scooter rulman, ninebot rulman, dualtron rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=scooter",
        alt_text="Sıra sıra elektrikli scooterlar; Yamansa e-scooter rulmanları",
        ig="E-scooter'ınızda tekerlek boşluk yaptı, sürüşte ses geldi mi? Rulman zamanı.\n\nXiaomi (M365, Pro, 1S, 3), Segway Ninebot, Dualtron, Navee, Citymate, Onvo, Hoofer, Volta modelleri için ince kesit ve standart rulmanlar stokta. NMB ve TPI Japon kalitesi seçenekleriyle.\n\nModelinizi yazın, doğru ölçüyü gönderelim.",
        li="Mikro mobilite pazarı büyüdükçe e-scooter servis ağı da genişliyor. Bu araçlarda kullanılan ince kesit rulmanlar (6800/6900 serisi) klasik motosiklet rulmanlarından farklı toleranslar ister.\n\nYamansa olarak Xiaomi, Segway Ninebot, Dualtron, Navee gibi markaların yaygın modelleri için rulman setlerini NMB, TPI ve Yamansa markalı seçeneklerle stoklu tutuyoruz. Servis ve filo işletmecileri için toplu tedarik mümkündür.",
        hashtags="scooter", blog="Elektrikli scooter rulmanı değişimi: Xiaomi M365 / Pro / Ninebot ölçüleri",
    ),
    dict(
        gun=9, tarih="29 Eyl 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6300",
        baslik="6300 SERİSİ<br>AĞIR HİZMET",
        alt="Aynı iç çap, daha kalın kesit, daha yüksek yük kapasitesi.",
        tablo=[("6300", "10 × 35 × 11"), ("6301", "12 × 37 × 12"), ("6302", "15 × 42 × 13"),
               ("6303", "17 × 47 × 14"), ("6304", "20 × 52 × 15"), ("6305", "25 × 62 × 17")],
        kw="6304 rulman, 6303 rulman, 6300 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6300",
        alt_text="6300 serisi rulman ölçü tablosu: 6300'den 6305'e ölçüler",
        ig="6300 serisi: 6200 ile aynı iç çap, daha kalın kesit, daha fazla yük.\n\n6300 → 10×35×11\n6301 → 12×37×12\n6302 → 15×42×13\n6303 → 17×47×14\n6304 → 20×52×15\n6305 → 25×62×17\n\nMotosiklet arka tekerlek, tarım makinesi, redüktör. Stok için DM.",
        hashtags="genel", blog="6300 serisi rulman ölçüleri – 6200 ile farkı",
    ),
    dict(
        gun=10, tarih="30 Eyl 2026 Çar", platform="IG, FB, LI", pillar="Teknik",
        sablon="bilgi", foto="8956445.jpg", etiket="TEKNİK BİLGİ",
        baslik="C3 BOŞLUK<br>NE DEMEK?",
        alt="Rulman iç boşluğu (radyal klerans) sınıfları.",
        liste=["C2 – Normalden dar: hassas, düşük ısı", "CN – Normal: genel kullanım (kodda yazılmaz)",
               "C3 – Geniş: ısınan miller, elektrik motoru", "C4 – Daha geniş: yüksek sıcaklık, ağır sanayi"],
        kw="c3 rulman ne demek, rulman boşluk sınıfı, c3 rulman farkı",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=c3",
        alt_text="Rulman iç boşluk sınıfları C2, CN, C3, C4 açıklama listesi",
        ig="C3 rulman ne demek? Rulmanın iç boşluğu (radyal klerans) normalden geniş demek.\n\nC2 → Dar (hassas, soğuk)\nCN → Normal (kodda yazmaz)\nC3 → Geniş (ısınan mil, elektrik motoru)\nC4 → Daha geniş (yüksek sıcaklık)\n\nMil çalışırken ısınıyor ve genleşiyorsa C3 alın. Aksi halde rulman sıkışır ve erken biter.",
        li="\"C3\" rulman kodlarında en çok yanlış anlaşılan ek. C3, kalite ya da marka değil; iç boşluk (radyal klerans) sınıfıdır.\n\nIsınan millerde iç bilezik genleşir ve normal boşluklu (CN) bir rulman sıkışabilir. Elektrik motorları, fanlar ve yüksek devirli uygulamalarda bu nedenle C3 tercih edilir.\n\nDoğru boşluk sınıfı seçimi, planlı bakım maliyetlerini doğrudan etkiler.",
        hashtags="teknik", blog="C3 rulman nedir? Boşluk sınıfları ve seçim rehberi",
    ),
    dict(
        gun=11, tarih="1 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="34240236.jpg", etiket="ARIZA TEŞHİSİ",
        baslik="RULMAN BİTTİ Mİ?<br>5 İŞARET",
        alt="Bu belirtilerden biri varsa rulmanı kontrol edin.",
        liste=["Hızla artan uğultu / vınlama sesi", "Tekerlekte yanal boşluk", "Gidonda veya milde titreşim",
               "Göbekte anormal ısınma", "Gres sızıntısı veya pas izi"],
        kw="rulman arızası belirtileri, tekerlek rulmanı sesi, rulman bozulduğu nasıl anlaşılır",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=ariza",
        alt_text="Motosiklet arka tekerlek fotoğrafı; rulman arızasının 5 belirtisi listesi",
        ig="Rulmanın bittiğini gösteren 5 işaret:\n\n1. Hızla artan uğultu\n2. Tekerlekte yanal boşluk\n3. Gidonda / milde titreşim\n4. Göbekte ısınma\n5. Gres sızıntısı veya pas\n\nBirini bile fark ettiyseniz bekletmeyin; bitmiş rulman göbeği ve mili de bozar. Ölçünüzü yazın, aynı gün gönderelim.",
        hashtags="moto", blog="Rulman arızası belirtileri: sesten titreşime 5 kontrol noktası",
    ),
    dict(
        gun=12, tarih="2 Eki 2026 Cum", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="hero", foto="36398150.jpg", etiket="İKİTELLİ OSB • İSTANBUL",
        baslik="STOKTAN,<br>AYNI GÜN KARGO.",
        alt="Saat 15:00'e kadar verilen siparişler aynı gün yola çıkar. Türkiye'nin her yerine.",
        kw="rulman kargo, hızlı rulman tedariki, rulmancı istanbul ikitelli",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=kargo",
        alt_text="Depo rafları ve forklift; Yamansa stoktan aynı gün kargo",
        ig="Makine durmuş, servis bekliyor. Rulman 'gelecek' değil, 'gitti' olmalı.\n\nİkitelli OSB'deki depomuzdan saat 15:00'e kadar verilen siparişler aynı gün kargoda. Binlerce kalem stok, günlük güncellenen stok bilgisi.\n\nyamansarulman.com üzerinden stok durumunu anlık görebilirsiniz.",
        li="Bakım duruşlarında en pahalı şey beklemektir. Bu nedenle stok politikamız net: en çok dönen serilerde derin stok, günlük güncellenen stok görünürlüğü ve saat 15:00'e kadar aynı gün sevkiyat.\n\nİkitelli OSB'deki depomuz Türkiye'nin her noktasına ertesi gün teslimat için konumlanmıştır. Bakım ekipleri ve satın alma birimleri için çerçeve anlaşma seçeneklerimiz vardır.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=13, tarih="3 Eki 2026 Cmt", platform="IG, FB", pillar="CTA",
        sablon="olcu", foto="19911421.jpg", etiket="ÖLÇÜNÜ YAZ",
        baslik="İÇ ÇAP × DIŞ ÇAP<br>× KALINLIK",
        alt="Üç ölçüyü yaz, gerisini bize bırak. Kodu bilmen gerekmez.",
        kw="ölçüye göre rulman bulma, rulman ölçü tablosu, rulman ölçüsü nasıl bulunur",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=olcu",
        alt_text="Rulman ölçüleri iç çap, dış çap ve kalınlık gösterimi",
        ig="Rulmanın üzerindeki kod silinmiş mi? Sorun değil.\n\nKumpasla üç ölçü al:\n• İç çap (d)\n• Dış çap (D)\n• Kalınlık (B)\n\nÖrn. 20 × 47 × 14 → 6204. DM'den yaz, kodunu ve fiyatını dakikalar içinde gönderelim. Sitemizdeki ölçü filtresiyle de kendin bulabilirsin: yamansarulman.com",
        hashtags="genel", blog="Ölçüye göre rulman bulma: iç çap / dış çap / kalınlık tablosu",
    ),
    dict(
        gun=14, tarih="4 Eki 2026 Paz", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="35568191.jpg", etiket="GRES",
        baslik="2RS'İN İÇİNDE<br>NE VAR?",
        alt="Keçeli rulmanlar ömür boyu yağlı gelir. Yeniden greslenmez.",
        liste=["Fabrikada lityum bazlı gres ile doldurulur", "Keçe, gresi içeride tutar; suyu dışarıda", "Ek gres basmak keçeyi bozar",
               "Ömrü bittiğinde rulman komple değişir"],
        kw="rulman gresi, keçeli rulman yağlama, 2rs rulman gres",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=gres",
        alt_text="Bilyalı rulman makro fotoğrafı; 2RS rulmanın içindeki gres hakkında bilgi listesi",
        ig="\"2RS rulmanı gresleyeyim mi?\" Hayır.\n\nKeçeli rulmanlar fabrikada lityum bazlı gresle dolu gelir; keçe gresi içeride, suyu dışarıda tutar. Keçeyi söküp gres basmak sızdırmazlığı bozar.\n\nÖmrü bitince yapılacak tek şey: yenisiyle değiştirmek. İyi pazarlar.",
        hashtags="teknik", blog="Rulman yağlama rehberi: açık, ZZ ve 2RS rulmanlarda gres",
    ),
    dict(
        gun=15, tarih="5 Eki 2026 Pzt", platform="IG, FB", pillar="Uygulama",
        sablon="split", foto="1595485.jpg", etiket="BİSİKLET",
        baslik="GÖBEK<br>RULMANLARI",
        alt="Salcano ve diğer markalar için ön/arka göbek, orta göbek ve pedal rulmanları.",
        kw="bisiklet göbek rulmanı, salcano rulman, bisiklet rulmanı ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=bisiklet",
        alt_text="Bisiklet ön tekerlek göbeği ve jant telleri; Yamansa bisiklet göbek rulmanları",
        ig="Bisiklette pedal çevirirken tıkırtı, tekerlekte ağır dönüş… Göbek rulmanı bakıyor.\n\nSalcano ve yaygın markalar için ön/arka göbek, orta göbek (BB) ve pedal rulmanları stokta. Çoğu model 6000/6800 serisi ince kesit kullanır; ölçüyü yaz, doğru rulmanı gönderelim.",
        hashtags="bisiklet", blog="Bisiklet göbek rulmanı ölçüleri ve değişim rehberi",
    ),
    dict(
        gun=16, tarih="6 Eki 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6000",
        baslik="6000 SERİSİ<br>HAFİF KESİT",
        alt="Küçük yer, yüksek devir: bisiklet, küçük motor, ev aletleri.",
        tablo=[("6000", "10 × 26 × 8"), ("6001", "12 × 28 × 8"), ("6002", "15 × 32 × 9"),
               ("6003", "17 × 35 × 10"), ("6004", "20 × 42 × 12"), ("6005", "25 × 47 × 12")],
        kw="6004 rulman, 6002 rulman, 6000 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6000",
        alt_text="6000 serisi rulman ölçü tablosu: 6000'den 6005'e ölçüler",
        ig="6000 serisi: en ince kesitli standart sabit bilyalı aile.\n\n6000 → 10×26×8\n6001 → 12×28×8\n6002 → 15×32×9\n6003 → 17×35×10\n6004 → 20×42×12\n6005 → 25×47×12\n\nBisiklet göbeği, küçük elektrik motorları, ev aletleri. Stokta.",
        hashtags="genel", blog="6000 serisi rulman ölçüleri ve muadilleri",
    ),
    dict(
        gun=17, tarih="7 Eki 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="hero", foto="4480986.jpg", etiket="B2B • BAYİ",
        baslik="TEK KAYNAK,<br>BÜTÜN MARKALAR.",
        alt="Rulmancılar, servisler ve makine imalatçıları için bayi fiyatlandırması ve düzenli tedarik.",
        kw="rulman toptan, rulman bayilik, rulman b2b tedarik",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=b2b",
        alt_text="Depoda görüşen ekip; Yamansa B2B bayi ve toptan rulman tedariki",
        ig="Rulmancı, servis ya da makine imalatçısı mısınız?\n\nSKF, FAG, ORS, NMB, TPI ve Yamansa markalarını tek kaynaktan, bayi fiyatıyla ve düzenli tedarikle alın. Sipariş geçmişiniz ve sık aldığınız ölçüler için özel liste.\n\nBayi başvurusu için DM veya 0212 670 02 05.",
        li="Çok markalı rulman tedarikinde en büyük maliyet, dağınık tedarik zinciridir: farklı tedarikçiler, farklı teslim süreleri, farklı fatura ve kalite standartları.\n\nYamansa, 1986'dan beri distribütörlüğünü yürüttüğü SKF, FAG, ORS, NMB ve TPI markalarını tek noktadan, tek faturayla ve günlük güncellenen stokla sunuyor. Rulmancılar, yetkili servisler ve OEM imalatçılar için bayi programımız hakkında bilgi almak isteyenler mesaj gönderebilir.",
        hashtags="sanayi", blog="Rulman bayiliği ve toptan tedarik: Yamansa B2B programı",
    ),
    dict(
        gun=18, tarih="8 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="38264258.jpg", etiket="MONTAJ",
        baslik="MONTAJDA<br>5 ÖLÜMCÜL HATA",
        alt="Yeni rulmanın erken bitmesinin en yaygın nedenleri.",
        liste=["Çekiçle doğrudan bileziğe vurmak", "Kuvveti yanlış bilezikten aktarmak", "Kirli el / kirli yuva",
               "Yanlış pres yönü ve eğik oturtma", "Fazla veya yanlış gres"],
        kw="rulman montajı nasıl yapılır, rulman takma hataları, rulman çakma",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=montaj",
        alt_text="Teknisyen elleri ve dişli parça; rulman montajında yapılan 5 hata listesi",
        ig="Yeni rulman 2 ayda mı bitti? Büyük ihtimalle montaj hatası.\n\n1. Çekiçle doğrudan bileziğe vurmak\n2. Kuvveti yanlış bilezikten aktarmak (mile takarken iç bilezikten, yuvaya takarken dış bilezikten bas)\n3. Kirli el, kirli yuva\n4. Eğik oturtma\n5. Fazla / yanlış gres\n\nMontaj kovanı veya pres kullanın. Kaydet, ustana gönder.",
        hashtags="teknik", blog="Rulman montajı: doğru yöntem, kovan ve pres kullanımı",
    ),
    dict(
        gun=19, tarih="9 Eki 2026 Cum", platform="IG, FB", pillar="Ürün",
        sablon="hero", foto="19911427.jpg", etiket="YAMANSA MARKA",
        baslik="BÜTÇE DOSTU,<br>TEST EDİLMİŞ.",
        alt="Yamansa markalı setler: seçilmiş üreticiler, kontrol edilmiş partiler, uygun fiyat.",
        kw="uygun fiyatlı rulman, yamansa rulman seti, ekonomik rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=yamansa-set",
        alt_text="Çelik bilyalı rulman ve bilyeler; Yamansa markalı ekonomik rulman setleri",
        ig="Her iş premium marka istemez; ama her iş güvenilir rulman ister.\n\nYamansa markalı setler: kendi konusunda uzmanlaşmış üreticilerden seçilen, parti bazında kontrol edilen rulmanlar. Motosiklet ve scooter setlerinde ideal fiyat/performans.\n\nAynı ölçüde SKF/FAG ile yan yana fiyat isteyin, karar sizin.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=20, tarih="10 Eki 2026 Cmt", platform="IG, FB, LI", pillar="Uygulama",
        sablon="markalar", foto="5450163.jpg", etiket="26 MARKA",
        baslik="HANGİ MOTOR,<br>HANGİ RULMAN?",
        alt="Model bazlı hazır setler. Aşağıdaki markaların tümü için stokta.",
        markalar=["HONDA", "YAMAHA", "BAJAJ", "KTM", "CFMOTO", "SUZUKI", "MONDIAL", "RKS", "KUBA", "TVS", "YUKI", "ARORA"],
        kw="yamaha rulman, ktm tekerlek rulmanı, mondial rulman, rks rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=moto-markalar",
        alt_text="Motosiklet ön tekerlek ve krom fren diski; 12 motosiklet markası logotip listesi",
        ig="Hangi motor, hangi rulman? Sormayın, biz biliyoruz.\n\nHonda • Yamaha • Bajaj • KTM • CFMOTO • Suzuki • Mondial • RKS • Kuba • TVS • Yuki • Arora • Falcon • Kanuni • Motolux • Asya • Volta…\n\n26 marka için ön/arka tekerlek rulman setleri hazır. Marka + model yaz, set fiyatını gönderelim.",
        li="Motosiklet sektöründe yerli montaj markaların (Mondial, RKS, Kuba, Yuki, Arora, Kanuni…) payı hızla artıyor ve bu modellerin rulman ölçüleri Japon markalarından farklılaşıyor.\n\nYamansa olarak 26 marka için model bazlı tekerlek rulman seti veri tabanı oluşturduk. Servis zincirleri ve yedek parça toptancıları için set bazında fiyatlandırma ve düzenli tedarik programı sunuyoruz.",
        hashtags="moto", blog="Motosiklet marka-model tekerlek rulmanı ölçü tablosu (26 marka)",
    ),
    dict(
        gun=21, tarih="11 Eki 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="7565159.jpg", etiket="PAZAR NOTU",
        baslik="“Kalite,<br>duyulmayan sestir.”",
        alt="Doğru rulman, doğru montaj, sessiz makine.",
        kw="kaliteli rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar2",
        alt_text="Karanlık zeminde kam mili fotoğrafı; alıntı: Kalite, duyulmayan sestir",
        ig="Kalite, duyulmayan sestir.\n\nİyi pazarlar. Yeni hafta sanayi tipi rulmanlarla başlıyor.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=22, tarih="12 Eki 2026 Pzt", platform="IG, FB, LI", pillar="Ürün",
        sablon="split", foto="2760241.jpg", etiket="SANAYİ",
        baslik="KONİK.<br>SİLİNDİRİK.<br>OYNAK.",
        alt="Redüktör, konveyör, pompa ve tezgâhlar için makaralı ve oynak bilyalı rulmanlar.",
        kw="konik makaralı rulman, silindirik makaralı rulman, oynak bilyalı rulman",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=sanayi",
        alt_text="Fabrikada büyük vidalı mil önünde mühendis; sanayi tipi konik, silindirik ve oynak rulmanlar",
        ig="Sadece motosiklet değil. Sanayi tarafında da 1986'dan beri buradayız.\n\n• Konik makaralı (30200/30300/32000 serileri)\n• Silindirik makaralı (NU/NJ/N serileri)\n• Oynak bilyalı (1200/2200 serileri)\n• Geniş kesitli ve yastıklı (UCP/UCF) rulmanlar\n\nRedüktör, konveyör, pompa, tezgâh. Ölçü ve kodunuzu yazın.",
        li="Sanayi uygulamalarında rulman seçimi yük tipiyle başlar: radyal yük için silindirik makaralı (NU, NJ), birleşik yük için konik makaralı (30200/30300), eksen kaçıklığı olan uzun millerde oynak bilyalı (1200/2200) rulmanlar.\n\nYamansa, bu ailelerin tümünü SKF, FAG ve ORS markalarıyla stoklamaktadır. Bakım planlaması yapan ekipler için kritik yedek listesi oluşturma desteği veriyoruz.",
        hashtags="sanayi", blog="Konik, silindirik ve oynak rulman: hangi yükte hangisi?",
    ),
    dict(
        gun=23, tarih="13 Eki 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="İNCE KESİT",
        baslik="6800 / 6900<br>İNCE KESİT",
        alt="E-scooter, drone, bisiklet ve robotik için dar alan rulmanları.",
        tablo=[("6800", "10 × 19 × 5"), ("6801", "12 × 21 × 5"), ("6802", "15 × 24 × 5"),
               ("6900", "10 × 22 × 6"), ("6901", "12 × 24 × 6"), ("6902", "15 × 28 × 7")],
        kw="6900 rulman, 6800 rulman, ince kesit rulman, 61900 rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=ince-kesit",
        alt_text="6800 ve 6900 serisi ince kesit rulman ölçü tablosu",
        ig="Dar alan, hafif yük, yüksek devir: 6800 ve 6900 serileri.\n\n6800 → 10×19×5\n6801 → 12×21×5\n6802 → 15×24×5\n6900 → 10×22×6\n6901 → 12×24×6\n6902 → 15×28×7\n\nE-scooter tekerlekleri, drone motorları, bisiklet göbekleri. NMB ve TPI seçenekleriyle stokta.",
        hashtags="scooter", blog="İnce kesit rulmanlar: 6700/6800/6900 serileri ölçü tablosu",
    ),
    dict(
        gun=24, tarih="14 Eki 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="istatistik", foto="4483608.jpg", etiket="STOK GÖRÜNÜRLÜĞÜ",
        baslik="STOK, HER GÜN<br>GÜNCELLENİR.",
        alt="Sitede gördüğünüz stok gerçek stok. Telefon açıp sormanıza gerek kalmaz.",
        sayilar=[("1986", "kuruluş yılı"), ("6", "distribütör marka"), ("26", "motosiklet & scooter markası"), ("15:00", "aynı gün kargo sınırı")],
        kw="rulman stok sorgulama, online rulman satış, rulman fiyat listesi",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=stok",
        alt_text="Depo rafları koridoru; Yamansa rakamlarla: 1986, 6 marka, 26 marka, 15:00 kargo",
        ig="\"Var mı?\" diye aramanıza gerek yok.\n\nyamansarulman.com'da gördüğünüz stok, o günün gerçek stoğu. Her sabah güncellenir. Ölçü filtresiyle iç çap / dış çap / kalınlık girin, stoktaki tüm markaları yan yana görün.\n\n1986'dan beri • 6 distribütör marka • 26 araç markası • 15:00'e kadar aynı gün kargo",
        li="B2B e-ticarette en büyük güven sorunu stok bilgisinin gerçek olmamasıdır. Yamansa'da ürün sayfalarındaki stok her gün otomatik olarak güncellenir; satın alma ekipleri telefonla doğrulama yapmak zorunda kalmaz.\n\nÖlçü tabanlı filtreleme (iç çap / dış çap / kalınlık) ile kod bilmeden doğru rulmana ulaşılır. Kurumsal müşteriler için fiyat listesi ve cari hesap seçenekleri mevcuttur.",
        hashtags="sanayi", blog="",
    ),
    dict(
        gun=25, tarih="15 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="14522449.jpg", etiket="3 ADIM",
        baslik="KUMPASLA<br>RULMAN ÖLÇÜMÜ",
        alt="Kod okunmuyorsa üç ölçü yeter.",
        liste=["İç çap (d): mile oturan deliği ölç", "Dış çap (D): en geniş dış kenarı ölç", "Kalınlık (B): bileziğin genişliğini ölç",
               "Kapak tipine bak: metal (ZZ) / kauçuk (2RS)"],
        kw="rulman ölçüsü nasıl alınır, kumpasla rulman ölçme, rulman iç çap dış çap",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=kumpas",
        alt_text="Metal makine parçası; kumpasla rulman ölçümü 3 adım listesi",
        ig="Kod silindi, rulman elimde: ne yapayım?\n\n1. İç çap (d) – mile oturan deliği ölç\n2. Dış çap (D) – dış kenarı ölç\n3. Kalınlık (B) – bilezik genişliğini ölç\n+ Kapak tipine bak: metal mi kauçuk mu?\n\n20 × 47 × 14 + kauçuk → 6204-2RS. Ölçüleri yaz, kodunu ve fiyatını gönderelim.",
        hashtags="teknik", blog="Kumpasla rulman ölçümü ve ölçüden kod bulma tablosu",
    ),
    dict(
        gun=26, tarih="16 Eki 2026 Cum", platform="IG, FB", pillar="Teknik",
        sablon="karsilastirma", foto="19911427.jpg", etiket="SIK SORULAN",
        baslik="6204 MÜ,<br>6304 MÜ?",
        alt="Aynı iç çap (20 mm), farklı kesit. Yuvaya bak, karar ver.",
        sol=("6204", "20 × 47 × 14", ["Standart kesit", "Yüksek devir", "Motor, pompa, fan", "Daha ekonomik"]),
        sag=("6304", "20 × 52 × 15", ["Kalın kesit", "Yüksek yük", "Tekerlek, tarım, redüktör", "Daha uzun ömür (ağır yük)"]),
        kw="6204 6304 farkı, 6204 rulman ölçüsü, 6304 rulman ölçüsü",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=6204-6304",
        alt_text="6204 ve 6304 rulman karşılaştırma tablosu",
        ig="6204 mü 6304 mü? İkisi de 20 mm iç çap; fark dış çapta ve yük kapasitesinde.\n\n6204 → 20×47×14 – standart kesit, yüksek devir, motor/pompa/fan\n6304 → 20×52×15 – kalın kesit, ağır yük, tekerlek/tarım/redüktör\n\nKural: Yuva ölçüsü neyse o. 47 mm yuvaya 6304 girmez; 52 mm yuvada 6204 döner ama tutmaz. Ölçüyü yaz, karar verelim.",
        hashtags="teknik", blog="6204 ve 6304 farkı: ölçü, yük ve kullanım alanı",
    ),
    dict(
        gun=27, tarih="17 Eki 2026 Cmt", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="split", foto="32845661.jpg", etiket="TEKNİK DESTEK",
        baslik="ÖLÇÜ. MUADİL.<br>MARKA<br>ÖNERİSİ.",
        alt="Kodunuzun muadilini, uygun marka ve kapak tipini birlikte belirleyelim. Ücretsiz.",
        kw="rulman muadil bulma, rulman teknik destek, rulman danışmanlık",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=teknik-destek",
        alt_text="CNC tezgâh başında mavi iş kıyafetli mühendis; Yamansa teknik destek",
        ig="Elinizdeki kod eski bir katalogdan mı? Üretimden kalkmış bir marka mı?\n\nEkibimiz muadil kodu, uygun markayı ve doğru kapak/boşluk tipini birlikte belirler. 40 yıla yakın tecrübe, ücretsiz.\n\nDM, WhatsApp veya 0212 670 02 05.",
        li="Bakım ekiplerinin sık karşılaştığı sorun: eski makinelerde üretimi durmuş ya da farklı standartta kodlanmış rulmanlar. Bu durumda doğru muadili bulmak, makinenin ömrünü belirler.\n\nYamansa teknik ekibi; ölçü doğrulama, muadil kod tespiti, marka ve boşluk sınıfı önerisini ücretsiz sunar. 1986'dan beri biriken saha tecrübesi, hızlı ve doğru karar için en güçlü aracımız.",
        hashtags="sanayi", blog="Rulman muadil tablosu: eski kodlardan yeni standarda geçiş",
    ),
    dict(
        gun=28, tarih="18 Eki 2026 Paz", platform="IG, FB", pillar="CTA",
        sablon="hero", foto="10294593.jpg", etiket="HAFTA SONU",
        baslik="ÖN + ARKA SET,<br>KARGO BİZDEN.",
        alt="Motosiklet ve scooter tekerlek rulmanı setlerinde bu hafta kargo ücretsiz. (Öneri – onayınıza bağlı)",
        kw="motosiklet rulman seti, ücretsiz kargo rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=set-kampanya",
        alt_text="Turuncu motosiklet jantı ve jant telleri; ön ve arka tekerlek rulman seti kampanyası",
        ig="Bu hafta motosiklet ve scooter tekerlek rulmanı setlerinde kargo bizden.\n\nÖn + arka seti birlikte al, ücretsiz kargoyla aynı gün yola çıksın. Marka + model yaz, set fiyatını gönderelim.\n\nKampanya 25 Ekim'e kadar geçerlidir.",
        hashtags="moto", blog="",
    ),
    dict(
        gun=29, tarih="19 Eki 2026 Pzt", platform="IG, FB, LI", pillar="Marka",
        sablon="istatistik", foto="29224559.jpg", etiket="1986 → 2026",
        baslik="40 YILA YAKIN<br>TECRÜBE.",
        alt="Üç kuşak rulmancı. Aynı adres, aynı ilke: doğru ürün, doğru fiyat, zamanında teslim.",
        sayilar=[("1986", "İkitelli'de kuruluş"), ("6", "distribütör marka"), ("3", "rulman ailesi: bilyalı, makaralı, oynak"), ("81", "ile aynı gün sevkiyat")],
        kw="rulman firması istanbul, köklü rulman tedarikçisi, yamansa rulman hakkında",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=40yil",
        alt_text="Fabrika üretim hattında çalışanlar; Yamansa 1986'dan 2026'ya rakamlar",
        ig="1986'da İkitelli'de küçük bir dükkânla başladı. Bugün 81 ile aynı gün sevkiyat yapan bir rulman tedarikçisiyiz.\n\nDeğişmeyen tek şey ilkemiz: doğru ürün, doğru fiyat, zamanında teslim.\n\nBizi takip ettiğiniz için teşekkürler.",
        li="Yamansa Rulman 1986'da İkitelli'de kuruldu. 40 yıla yaklaşan sürede rulman ithalatı ve distribütörlüğünde uzmanlaştık; kendi alanında uzman üreticilerin yeni nesil rulmanlarını Türkiye pazarına sunduk.\n\nBugün SKF, FAG, ORS, NMB, TPI ve Yamansa markalı ürünlerle sanayi, motosiklet ve mikro mobilite sektörlerine hizmet veriyoruz. Yeni dönemde dijital stok görünürlüğü ve B2B çevrimiçi sipariş ile büyümeye devam ediyoruz.",
        hashtags="genel", blog="Yamansa Rulman hikâyesi: 1986'dan bugüne",
    ),
    dict(
        gun=30, tarih="20 Eki 2026 Sal", platform="IG, FB, LI", pillar="CTA",
        sablon="hero", foto="19911421.jpg", etiket="KATALOG",
        baslik="ÖLÇÜNÜ GİR,<br>RULMANINI BUL.",
        alt="İç çap / dış çap / kalınlık filtresiyle tüm markaları yan yana karşılaştır. yamansarulman.com",
        kw="online rulman katalog, rulman ölçü filtresi, rulman satın al",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=katalog",
        alt_text="Çelik rulman bilezikleri ve bilyeler; Yamansa online katalog çağrısı",
        ig="Bir aydır anlattık: kod okuma, ZZ/2RS, C3, ölçü alma, montaj…\n\nŞimdi sıra sizde: yamansarulman.com'a gir, ölçünü yaz, stoktaki tüm markaları fiyatıyla gör. Saat 15:00'e kadar sipariş, aynı gün kargo.\n\nKaçırdığınız gönderiler için profilimize göz atın. Sorularınız için DM her zaman açık.",
        li="Bir aylık içerik serimizde rulman kodlarını, kapak ve boşluk sınıflarını, ölçü almayı ve montaj hatalarını ele aldık. Tüm içeriklere sayfamızdan ulaşabilirsiniz.\n\nÖlçü tabanlı çevrimiçi kataloğumuz yamansarulman.com adresinde: iç çap / dış çap / kalınlık girin, stoktaki markaları karşılaştırın. Kurumsal tedarik için ekibimizle iletişime geçin.",
        hashtags="genel", blog="Site içi arama ve ölçü filtresi kullanım rehberi",
    ),
]

# LinkedIn günlerinde kullanılacak kısa hashtag seti
LI_HASHTAGS = "#rulman #bearings #endüstri #tedarikzinciri #bakım"
