# -*- coding: utf-8 -*-
"""Yamansa Rulman – 60 günlük (2 ay) içerik planının tek kaynağı.

Hem takvim dosyaları (MD/CSV) hem de görseller bu listeden üretilir.
"""

SITE = "https://www.yamansarulman.com"
TEL = "0552 610 93 63"
ADRES = "İkitelli OSB, Heskop San. Sit. M4 Blok No:47, Başakşehir / İstanbul"

# Ortak hashtag setleri (Instagram/Facebook için). LinkedIn'de en fazla 3-5 tanesi kullanılır.
HASHTAG_SETS = {
    "genel": "#rulman #yamansarulman #rulmanfiyatları #sanayi #yedekparça #istanbul #ikitelli",
    "moto": "#motosiklet #motosikletyedekparça #tekerlekrulmanı #motorrulmanı #honda #yamaha #bajaj #ktm #cfmoto #mondial",
    "scooter": "#elektrikliscooter #scooter #xiaomi #segway #ninebot #dualtron #navee #scooteryedekparça",
    "teknik": "#rulmanteknik #makinebakım #bakımonarım #mühendislik #tekniker",
    "bisiklet": "#bisiklet #salcano #bisikletyedekparça #bisiklettamir",
    "sanayi": "#endüstri #makineimalat #fabrika #bakım #konikrulman #silindirikrulman",
    "beyazesya": "#çamaşırmakinesi #beyazeşya #beyazeşyatamir #çamaşırmakinesirulmanı #rulman #yamansarulman",
    "kaykay": "#kaykay #paten #608rulman #longboard #rulman #yamansarulman",
    "29ekim": "#29Ekim #CumhuriyetBayramı #Cumhuriyet #yamansarulman",
    "10kasim": "#10Kasım #Atatürk #SaygıylaAnıyoruz #yamansarulman",
}

# Her kayıt: görsel şablonu + platform metinleri + SEO alanları
POSTS = [
    dict(
        gun=1, tarih="21 Eyl 2026 Pzt", platform="IG, FB, LI", pillar="Marka",
        sablon="hero", foto="19911427.jpg", etiket="1986'DAN BERİ",
        baslik="RULMANDA<br>DOĞRU ADRES.",
        alt="Sabit bilyalı, konik, silindirik ve oynak rulmanlar – orijinal, faturalı, stoktan aynı gün kargo.",
        kw="rulman, rulman tedarikçisi İstanbul, rulman satış",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=lansman",
        alt_text="Yamansa Rulman açılış gönderisi: çelik bilyalı rulman fotoğrafı üzerinde 'Rulmanda doğru adres' başlığı",
        ig="Yamansa Rulman artık sosyal medyada! 1986'dan beri İkitelli OSB'den tüm Türkiye'ye rulman tedarik ediyoruz.\n\n• SKF, FAG, ORS, NMB, TPI ve Yamansa markalı setler\n• Motosiklet, scooter, bisiklet ve sanayi rulmanları\n• Stoktan aynı gün kargo, faturalı ve orijinal ürün\n\nÖlçünüzü yazın, doğru rulmanı bulalım. Katalog: yamansarulman.com",
        li="Yamansa Rulman olarak 1986'dan bu yana rulman ithalatı ve distribütörlüğü yapıyoruz. Bu sayfada sektör bilgisi, ürün serileri ve tedarik süreçlerimizi paylaşacağız.\n\nOdak alanlarımız: sabit bilyalı rulmanlar (ZZ/2RS), motosiklet ve e-scooter tekerlek rulmanları, sanayi tipi konik ve silindirik makaralı rulmanlar. Distribütörlüğünü yürüttüğümüz markalar: SKF, FAG, ORS, NMB, TPI.\n\nBayi ve toplu alım talepleri için: yamansarulman.com",
        hashtags="genel", blog="Yamansa Rulman hakkında: 1986'dan bugüne (Hakkımızda sayfası SEO metni)",
    ),
    dict(
        gun=2, tarih="22 Eyl 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6200",
        baslik="6200 SERİSİ<br>SABİT BİLYALI",
        alt="En çok aranan ölçüler stokta. ZZ (metal kapak) ve 2RS (kauçuk keçe) seçenekleri.",
        tablo=[("6200", "10 × 30 × 9"), ("6201", "12 × 32 × 10"), ("6202", "15 × 35 × 11"),
               ("6203", "17 × 40 × 12"), ("6204", "20 × 47 × 14"), ("6205", "25 × 52 × 15")],
        kw="6204 rulman, 6203 rulman, 6200 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6200",
        alt_text="6200 serisi rulman ölçü tablosu: 6200'den 6205'e iç çap, dış çap ve kalınlık",
        ig="6200 serisi, sanayide ve motosiklette en çok kullanılan sabit bilyalı rulman ailesi.\n\n6200 → 10×30×9\n6201 → 12×32×10\n6202 → 15×35×11\n6203 → 17×40×12\n6204 → 20×47×14\n6205 → 25×52×15\n\nZZ mi 2RS mi? Yarın anlatıyoruz. Fiyat ve stok için DM veya yamansarulman.com",
        hashtags="genel", blog="6200 serisi rulman ölçüleri ve kullanım alanları (ölçü tablosu sayfası)",
    ),
    dict(
        gun=3, tarih="23 Eyl 2026 Çar", platform="IG, FB, LI", pillar="Teknik",
        sablon="karsilastirma", foto="35568191.jpg", etiket="TEKNİK BİLGİ",
        baslik="ZZ Mİ,<br>2RS Mİ?",
        alt="Kapak tipi seçimi rulman ömrünü belirler.",
        sol=("ZZ", "Metal kapak", ["Yüksek devir", "Düşük sürtünme", "Toz koruması", "Kuru ortam"]),
        sag=("2RS", "Kauçuk keçe", ["Su & çamur koruması", "Gres içinde kalır", "Tekerlek / dış ortam", "Orta devir"]),
        kw="zz rulman 2rs rulman farkı, kapaklı rulman keçeli rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=zz-2rs",
        alt_text="ZZ metal kapaklı ve 2RS kauçuk keçeli rulman karşılaştırma grafiği",
        ig="ZZ mi 2RS mi? En çok aldığımız soru.\n\nZZ (metal kapak): yüksek devir, düşük sürtünme, kuru ve temiz ortam. Elektrik motoru, fan, spindle.\n\n2RS (kauçuk keçe): su, çamur ve toza karşı tam koruma; gres içinde kalır. Motosiklet ve scooter tekerlekleri, dış ortam.\n\nKural: Tekerlekse 2RS, motorsa ZZ. Emin değilseniz ölçüyü yazın, birlikte seçelim.",
        li="Rulman seçiminde kapak tipi çoğu zaman ihmal edilir; oysa arızaların önemli bir kısmı yanlış kapak seçiminden kaynaklanır.\n\nZZ (metal kapak): düşük sürtünme ve yüksek devir; toz koruması sağlar, sıvıya karşı korumaz. Elektrik motorları ve fanlar için idealdir.\n\n2RS (kauçuk keçe): su ve çamura karşı temas eden sızdırmazlık; gres rulman içinde kalır. Tekerlek, dış ortam ve yıkamaya maruz uygulamalar için tercih edilir.\n\nDoğru seçim, doğru ömür. Teknik danışmanlık için ekibimizle iletişime geçebilirsiniz.",
        hashtags="teknik", blog="ZZ ve 2RS rulman farkı nedir? Hangi uygulamada hangisi kullanılır?",
    ),
    dict(
        gun=4, tarih="24 Eyl 2026 Per", platform="IG, FB, LI", pillar="Uygulama",
        sablon="split", foto="18171624.jpg", etiket="MOTOSİKLET",
        baslik="TEKERLEK<br>RULMANI<br>SETLERİ",
        alt="Honda, Yamaha, Bajaj, KTM, CFMOTO, Mondial, RKS, Kuba, Suzuki ve daha fazlası için ön/arka tekerlek rulman setleri.",
        kw="motosiklet tekerlek rulmanı, honda tekerlek rulmanı, bajaj rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=moto-tekerlek",
        alt_text="Motosiklet ön tekerlek ve fren diski fotoğrafı; Yamansa motosiklet tekerlek rulmanı setleri",
        ig="Tekerlekten uğultu mu geliyor? Direksiyonda titreşim mi var? Büyük ihtimalle tekerlek rulmanı.\n\nHonda, Yamaha, Bajaj, KTM, CFMOTO, Mondial, RKS, Kuba, Suzuki, TVS, Yuki, Arora, Falcon… 26 marka için ön ve arka tekerlek rulman setlerimiz hazır.\n\nModelinizi yazın, doğru seti aynı gün kargolayalım.",
        li="Motosiklet servisleri için en sık değişen parçalardan biri tekerlek rulmanı. Yanlış ölçü ya da düşük kaliteli rulman, birkaç ay içinde aynı arızayı tekrarlatır.\n\nYamansa olarak 26 motosiklet markası için model bazlı ön/arka tekerlek rulman setleri hazırladık; SKF, FAG, ORS veya Yamansa markalı alternatiflerle. Servisler ve yedek parça bayileri için toplu fiyatlandırma mevcuttur.",
        hashtags="moto", blog="Motosiklet tekerlek rulmanı nasıl anlaşılır, nasıl değişir? Marka-model ölçü rehberi",
    ),
    dict(
        gun=5, tarih="25 Eyl 2026 Cum", platform="IG, FB", pillar="Marka",
        sablon="markalar", foto="7565159.jpg", etiket="DİSTRİBÜTÖR",
        baslik="ORİJİNAL.<br>FATURALI.<br>STOKTAN.",
        alt="Distribütörlüğünü yürüttüğümüz ve stoklarımızda bulunan markalar.",
        markalar=["SKF", "FAG", "ORS", "NMB", "TPI", "YAMANSA"],
        kw="skf rulman, fag rulman, ors rulman, orijinal rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=markalar",
        alt_text="SKF, FAG, ORS, NMB, TPI ve Yamansa marka logotipleri; orijinal faturalı rulman",
        ig="Piyasada sahte rulman var, biliyoruz. Bizde yok.\n\nSKF • FAG • ORS • NMB • TPI • Yamansa\n\nHer ürün orijinal, faturalı ve stoktan. 1986'dan beri aynı adreste, aynı ilkeyle.\n\nMarka tercihini yaz, fiyatı gönderelim.",
        hashtags="genel", blog="Sahte rulman nasıl anlaşılır? Orijinal SKF/FAG rulman kontrol rehberi",
    ),
    dict(
        gun=6, tarih="26 Eyl 2026 Cmt", platform="IG, FB", pillar="Teknik",
        sablon="kod", foto="20607184.jpg", etiket="NASIL OKUNUR?",
        baslik="RULMAN KODU<br>NASIL OKUNUR?",
        alt="Örnek: 6204-2RS C3",
        kod=[("62", "Seri (sabit bilyalı, orta)"), ("04", "İç çap: 04 × 5 = 20 mm"),
             ("2RS", "İki taraf kauçuk keçe"), ("C3", "Normalden geniş boşluk")],
        kw="rulman kodu okuma, rulman numarası ne anlama gelir, 6204 2rs c3",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=rulman-kodu",
        alt_text="6204-2RS C3 rulman kodunun parçalara ayrılmış açıklaması",
        ig="6204-2RS C3 ne demek?\n\n62 → Seri (sabit bilyalı, orta yük)\n04 → İç çap kodu: 04×5 = 20 mm\n2RS → İki tarafı kauçuk keçeli\nC3 → Normalden geniş iç boşluk (ısınan uygulamalar)\n\nNot: 00=10, 01=12, 02=15, 03=17 mm; 04'ten sonrası ×5.\n\nKaydet, lazım olur. Sorularınızı yoruma yazın.",
        hashtags="teknik", blog="Rulman kodları nasıl okunur? Tam rehber (ek harfler, boşluk sınıfları)",
    ),
    dict(
        gun=7, tarih="27 Eyl 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="35568191.jpg", etiket="PAZAR NOTU",
        baslik="“Bir makinenin sesi,<br>rulmanının sağlığıdır.”",
        alt="İyi bir rulman kendini duyurmaz; yalnızca çalışır.",
        kw="rulman bakımı, rulman sesi",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar",
        alt_text="Makro çekim bilyalı rulman fotoğrafı üzerine alıntı: Bir makinenin sesi, rulmanının sağlığıdır",
        ig="Bir makinenin sesi, rulmanının sağlığıdır.\n\nİyi haftalar. Pazartesi e-scooter rulmanlarıyla devam ediyoruz.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=8, tarih="28 Eyl 2026 Pzt", platform="IG, FB, LI", pillar="Uygulama",
        sablon="split", foto="38292508.jpg", etiket="E-SCOOTER",
        baslik="SCOOTER<br>RULMANLARI<br>STOKTA",
        alt="Xiaomi, Segway Ninebot, Dualtron, Navee, Citymate, Onvo, Hoofer, Volta için tekerlek ve motor rulmanları.",
        kw="scooter rulmanı, xiaomi scooter rulman, ninebot rulman, dualtron rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=scooter",
        alt_text="Sıra sıra elektrikli scooterlar; Yamansa e-scooter rulmanları",
        ig="E-scooter'ınızda tekerlek boşluk yaptı, sürüşte ses geldi mi? Rulman zamanı.\n\nXiaomi (M365, Pro, 1S, 3), Segway Ninebot, Dualtron, Navee, Citymate, Onvo, Hoofer, Volta modelleri için ince kesit ve standart rulmanlar stokta. NMB ve TPI Japon kalitesi seçenekleriyle.\n\nModelinizi yazın, doğru ölçüyü gönderelim.",
        li="Mikro mobilite pazarı büyüdükçe e-scooter servis ağı da genişliyor. Bu araçlarda kullanılan ince kesit rulmanlar (6800/6900 serisi) klasik motosiklet rulmanlarından farklı toleranslar ister.\n\nYamansa olarak Xiaomi, Segway Ninebot, Dualtron, Navee gibi markaların yaygın modelleri için rulman setlerini NMB, TPI ve Yamansa markalı seçeneklerle stoklu tutuyoruz. Servis ve filo işletmecileri için toplu tedarik mümkündür.",
        hashtags="scooter", blog="Elektrikli scooter rulmanı değişimi: Xiaomi M365 / Pro / Ninebot ölçüleri",
    ),
    dict(
        gun=9, tarih="29 Eyl 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6300",
        baslik="6300 SERİSİ<br>AĞIR HİZMET",
        alt="Aynı iç çap, daha kalın kesit, daha yüksek yük kapasitesi.",
        tablo=[("6300", "10 × 35 × 11"), ("6301", "12 × 37 × 12"), ("6302", "15 × 42 × 13"),
               ("6303", "17 × 47 × 14"), ("6304", "20 × 52 × 15"), ("6305", "25 × 62 × 17")],
        kw="6304 rulman, 6303 rulman, 6300 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6300",
        alt_text="6300 serisi rulman ölçü tablosu: 6300'den 6305'e ölçüler",
        ig="6300 serisi: 6200 ile aynı iç çap, daha kalın kesit, daha fazla yük.\n\n6300 → 10×35×11\n6301 → 12×37×12\n6302 → 15×42×13\n6303 → 17×47×14\n6304 → 20×52×15\n6305 → 25×62×17\n\nMotosiklet arka tekerlek, tarım makinesi, redüktör. Stok için DM.",
        hashtags="genel", blog="6300 serisi rulman ölçüleri – 6200 ile farkı",
    ),
    dict(
        gun=10, tarih="30 Eyl 2026 Çar", platform="IG, FB, LI", pillar="Teknik",
        sablon="bilgi", foto="8956445.jpg", etiket="TEKNİK BİLGİ",
        baslik="C3 BOŞLUK<br>NE DEMEK?",
        alt="Rulman iç boşluğu (radyal klerans) sınıfları.",
        liste=["C2 – Normalden dar: hassas, düşük ısı", "CN – Normal: genel kullanım (kodda yazılmaz)",
               "C3 – Geniş: ısınan miller, elektrik motoru", "C4 – Daha geniş: yüksek sıcaklık, ağır sanayi"],
        kw="c3 rulman ne demek, rulman boşluk sınıfı, c3 rulman farkı",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=c3",
        alt_text="Rulman iç boşluk sınıfları C2, CN, C3, C4 açıklama listesi",
        ig="C3 rulman ne demek? Rulmanın iç boşluğu (radyal klerans) normalden geniş demek.\n\nC2 → Dar (hassas, soğuk)\nCN → Normal (kodda yazmaz)\nC3 → Geniş (ısınan mil, elektrik motoru)\nC4 → Daha geniş (yüksek sıcaklık)\n\nMil çalışırken ısınıyor ve genleşiyorsa C3 alın. Aksi halde rulman sıkışır ve erken biter.",
        li="\"C3\" rulman kodlarında en çok yanlış anlaşılan ek. C3, kalite ya da marka değil; iç boşluk (radyal klerans) sınıfıdır.\n\nIsınan millerde iç bilezik genleşir ve normal boşluklu (CN) bir rulman sıkışabilir. Elektrik motorları, fanlar ve yüksek devirli uygulamalarda bu nedenle C3 tercih edilir.\n\nDoğru boşluk sınıfı seçimi, planlı bakım maliyetlerini doğrudan etkiler.",
        hashtags="teknik", blog="C3 rulman nedir? Boşluk sınıfları ve seçim rehberi",
    ),
    dict(
        gun=11, tarih="1 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="29408661.jpg", etiket="ARIZA TEŞHİSİ",
        baslik="RULMAN BİTTİ Mİ?<br>5 İŞARET",
        alt="Bu belirtilerden biri varsa rulmanı kontrol edin.",
        liste=["Hızla artan uğultu / vınlama sesi", "Tekerlekte yanal boşluk", "Gidonda veya milde titreşim",
               "Göbekte anormal ısınma", "Gres sızıntısı veya pas izi"],
        kw="rulman arızası belirtileri, tekerlek rulmanı sesi, rulman bozulduğu nasıl anlaşılır",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=ariza",
        alt_text="Motosiklet jant göbeği ve tel jant yakın çekim; rulman arızasının 5 belirtisi listesi",
        ig="Rulmanın bittiğini gösteren 5 işaret:\n\n1. Hızla artan uğultu\n2. Tekerlekte yanal boşluk\n3. Gidonda / milde titreşim\n4. Göbekte ısınma\n5. Gres sızıntısı veya pas\n\nBirini bile fark ettiyseniz bekletmeyin; bitmiş rulman göbeği ve mili de bozar. Ölçünüzü yazın, aynı gün gönderelim.",
        hashtags="moto", blog="Rulman arızası belirtileri: sesten titreşime 5 kontrol noktası",
    ),
    dict(
        gun=12, tarih="2 Eki 2026 Cum", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="hero", foto="36398150.jpg", etiket="İKİTELLİ OSB • İSTANBUL",
        baslik="STOKTAN,<br>AYNI GÜN KARGO.",
        alt="Saat 15:00'e kadar verilen siparişler aynı gün yola çıkar. Türkiye'nin her yerine.",
        kw="rulman kargo, hızlı rulman tedariki, rulmancı istanbul ikitelli",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=kargo",
        alt_text="Depo rafları ve forklift; Yamansa stoktan aynı gün kargo",
        ig="Makine durmuş, servis bekliyor. Rulman 'gelecek' değil, 'gitti' olmalı.\n\nİkitelli OSB'deki depomuzdan saat 15:00'e kadar verilen siparişler aynı gün kargoda. Binlerce kalem stok, günlük güncellenen stok bilgisi.\n\nyamansarulman.com üzerinden stok durumunu anlık görebilirsiniz.",
        li="Bakım duruşlarında en pahalı şey beklemektir. Bu nedenle stok politikamız net: en çok dönen serilerde derin stok, günlük güncellenen stok görünürlüğü ve saat 15:00'e kadar aynı gün sevkiyat.\n\nİkitelli OSB'deki depomuz Türkiye'nin her noktasına ertesi gün teslimat için konumlanmıştır. Bakım ekipleri ve satın alma birimleri için çerçeve anlaşma seçeneklerimiz vardır.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=13, tarih="3 Eki 2026 Cmt", platform="IG, FB", pillar="CTA",
        sablon="olcu", foto="19911421.jpg", etiket="ÖLÇÜNÜ YAZ",
        baslik="İÇ ÇAP × DIŞ ÇAP<br>× KALINLIK",
        alt="Üç ölçüyü yaz, gerisini bize bırak. Kodu bilmen gerekmez.",
        kw="ölçüye göre rulman bulma, rulman ölçü tablosu, rulman ölçüsü nasıl bulunur",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=olcu",
        alt_text="Rulman ölçüleri iç çap, dış çap ve kalınlık gösterimi",
        ig="Rulmanın üzerindeki kod silinmiş mi? Sorun değil.\n\nKumpasla üç ölçü al:\n• İç çap (d)\n• Dış çap (D)\n• Kalınlık (B)\n\nÖrn. 20 × 47 × 14 → 6204. DM'den yaz, kodunu ve fiyatını dakikalar içinde gönderelim. Sitemizdeki ölçü filtresiyle de kendin bulabilirsin: yamansarulman.com",
        hashtags="genel", blog="Ölçüye göre rulman bulma: iç çap / dış çap / kalınlık tablosu",
    ),
    dict(
        gun=14, tarih="4 Eki 2026 Paz", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="35568191.jpg", etiket="GRES",
        baslik="2RS'İN İÇİNDE<br>NE VAR?",
        alt="Keçeli rulmanlar ömür boyu yağlı gelir. Yeniden greslenmez.",
        liste=["Fabrikada lityum bazlı gres ile doldurulur", "Keçe, gresi içeride tutar; suyu dışarıda", "Ek gres basmak keçeyi bozar",
               "Ömrü bittiğinde rulman komple değişir"],
        kw="rulman gresi, keçeli rulman yağlama, 2rs rulman gres",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=gres",
        alt_text="Bilyalı rulman makro fotoğrafı; 2RS rulmanın içindeki gres hakkında bilgi listesi",
        ig="\"2RS rulmanı gresleyeyim mi?\" Hayır.\n\nKeçeli rulmanlar fabrikada lityum bazlı gresle dolu gelir; keçe gresi içeride, suyu dışarıda tutar. Keçeyi söküp gres basmak sızdırmazlığı bozar.\n\nÖmrü bitince yapılacak tek şey: yenisiyle değiştirmek. İyi pazarlar.",
        hashtags="teknik", blog="Rulman yağlama rehberi: açık, ZZ ve 2RS rulmanlarda gres",
    ),
    dict(
        gun=15, tarih="5 Eki 2026 Pzt", platform="IG, FB", pillar="Uygulama",
        sablon="split", foto="1595485.jpg", etiket="BİSİKLET",
        baslik="GÖBEK<br>RULMANLARI",
        alt="Salcano ve diğer markalar için ön/arka göbek, orta göbek ve pedal rulmanları.",
        kw="bisiklet göbek rulmanı, salcano rulman, bisiklet rulmanı ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=bisiklet",
        alt_text="Bisiklet ön tekerlek göbeği ve jant telleri; Yamansa bisiklet göbek rulmanları",
        ig="Bisiklette pedal çevirirken tıkırtı, tekerlekte ağır dönüş… Göbek rulmanı bakıyor.\n\nSalcano ve yaygın markalar için ön/arka göbek, orta göbek (BB) ve pedal rulmanları stokta. Çoğu model 6000/6800 serisi ince kesit kullanır; ölçüyü yaz, doğru rulmanı gönderelim.",
        hashtags="bisiklet", blog="Bisiklet göbek rulmanı ölçüleri ve değişim rehberi",
    ),
    dict(
        gun=16, tarih="6 Eki 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6000",
        baslik="6000 SERİSİ<br>HAFİF KESİT",
        alt="Küçük yer, yüksek devir: bisiklet, küçük motor, ev aletleri.",
        tablo=[("6000", "10 × 26 × 8"), ("6001", "12 × 28 × 8"), ("6002", "15 × 32 × 9"),
               ("6003", "17 × 35 × 10"), ("6004", "20 × 42 × 12"), ("6005", "25 × 47 × 12")],
        kw="6004 rulman, 6002 rulman, 6000 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6000",
        alt_text="6000 serisi rulman ölçü tablosu: 6000'den 6005'e ölçüler",
        ig="6000 serisi: en ince kesitli standart sabit bilyalı aile.\n\n6000 → 10×26×8\n6001 → 12×28×8\n6002 → 15×32×9\n6003 → 17×35×10\n6004 → 20×42×12\n6005 → 25×47×12\n\nBisiklet göbeği, küçük elektrik motorları, ev aletleri. Stokta.",
        hashtags="genel", blog="6000 serisi rulman ölçüleri ve muadilleri",
    ),
    dict(
        gun=17, tarih="7 Eki 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="hero", foto="4480986.jpg", etiket="B2B • BAYİ",
        baslik="TEK KAYNAK,<br>BÜTÜN MARKALAR.",
        alt="Rulmancılar, servisler ve makine imalatçıları için bayi fiyatlandırması ve düzenli tedarik.",
        kw="rulman toptan, rulman bayilik, rulman b2b tedarik",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=b2b",
        alt_text="Depoda görüşen ekip; Yamansa B2B bayi ve toptan rulman tedariki",
        ig="Rulmancı, servis ya da makine imalatçısı mısınız?\n\nSKF, FAG, ORS, NMB, TPI ve Yamansa markalarını tek kaynaktan, bayi fiyatıyla ve düzenli tedarikle alın. Sipariş geçmişiniz ve sık aldığınız ölçüler için özel liste.\n\nBayi başvurusu için DM veya 0552 610 93 63.",
        li="Çok markalı rulman tedarikinde en büyük maliyet, dağınık tedarik zinciridir: farklı tedarikçiler, farklı teslim süreleri, farklı fatura ve kalite standartları.\n\nYamansa, 1986'dan beri distribütörlüğünü yürüttüğü SKF, FAG, ORS, NMB ve TPI markalarını tek noktadan, tek faturayla ve günlük güncellenen stokla sunuyor. Rulmancılar, yetkili servisler ve OEM imalatçılar için bayi programımız hakkında bilgi almak isteyenler mesaj gönderebilir.",
        hashtags="sanayi", blog="Rulman bayiliği ve toptan tedarik: Yamansa B2B programı",
    ),
    dict(
        gun=18, tarih="8 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="38264258.jpg", etiket="MONTAJ",
        baslik="MONTAJDA<br>5 ÖLÜMCÜL HATA",
        alt="Yeni rulmanın erken bitmesinin en yaygın nedenleri.",
        liste=["Çekiçle doğrudan bileziğe vurmak", "Kuvveti yanlış bilezikten aktarmak", "Kirli el / kirli yuva",
               "Yanlış pres yönü ve eğik oturtma", "Fazla veya yanlış gres"],
        kw="rulman montajı nasıl yapılır, rulman takma hataları, rulman çakma",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=montaj",
        alt_text="Teknisyen elleri ve dişli parça; rulman montajında yapılan 5 hata listesi",
        ig="Yeni rulman 2 ayda mı bitti? Büyük ihtimalle montaj hatası.\n\n1. Çekiçle doğrudan bileziğe vurmak\n2. Kuvveti yanlış bilezikten aktarmak (mile takarken iç bilezikten, yuvaya takarken dış bilezikten bas)\n3. Kirli el, kirli yuva\n4. Eğik oturtma\n5. Fazla / yanlış gres\n\nMontaj kovanı veya pres kullanın. Kaydet, ustana gönder.",
        hashtags="teknik", blog="Rulman montajı: doğru yöntem, kovan ve pres kullanımı",
    ),
    dict(
        gun=19, tarih="9 Eki 2026 Cum", platform="IG, FB", pillar="Ürün",
        sablon="hero", foto="19911427.jpg", etiket="YAMANSA MARKA",
        baslik="BÜTÇE DOSTU,<br>TEST EDİLMİŞ.",
        alt="Yamansa markalı setler: seçilmiş üreticiler, kontrol edilmiş partiler, uygun fiyat.",
        kw="uygun fiyatlı rulman, yamansa rulman seti, ekonomik rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=yamansa-set",
        alt_text="Çelik bilyalı rulman ve bilyeler; Yamansa markalı ekonomik rulman setleri",
        ig="Her iş premium marka istemez; ama her iş güvenilir rulman ister.\n\nYamansa markalı setler: kendi konusunda uzmanlaşmış üreticilerden seçilen, parti bazında kontrol edilen rulmanlar. Motosiklet ve scooter setlerinde ideal fiyat/performans.\n\nAynı ölçüde SKF/FAG ile yan yana fiyat isteyin, karar sizin.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=20, tarih="10 Eki 2026 Cmt", platform="IG, FB, LI", pillar="Uygulama",
        sablon="markalar", foto="5450163.jpg", etiket="26 MARKA",
        baslik="HANGİ MOTOR,<br>HANGİ RULMAN?",
        alt="Model bazlı hazır setler. Aşağıdaki markaların tümü için stokta.",
        markalar=["HONDA", "YAMAHA", "BAJAJ", "KTM", "CFMOTO", "SUZUKI", "MONDIAL", "RKS", "KUBA", "TVS", "YUKI", "ARORA"],
        kw="yamaha rulman, ktm tekerlek rulmanı, mondial rulman, rks rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=moto-markalar",
        alt_text="Motosiklet ön tekerlek ve krom fren diski; 12 motosiklet markası logotip listesi",
        ig="Hangi motor, hangi rulman? Sormayın, biz biliyoruz.\n\nHonda • Yamaha • Bajaj • KTM • CFMOTO • Suzuki • Mondial • RKS • Kuba • TVS • Yuki • Arora • Falcon • Kanuni • Motolux • Asya • Volta…\n\n26 marka için ön/arka tekerlek rulman setleri hazır. Marka + model yaz, set fiyatını gönderelim.",
        li="Motosiklet sektöründe yerli montaj markaların (Mondial, RKS, Kuba, Yuki, Arora, Kanuni…) payı hızla artıyor ve bu modellerin rulman ölçüleri Japon markalarından farklılaşıyor.\n\nYamansa olarak 26 marka için model bazlı tekerlek rulman seti veri tabanı oluşturduk. Servis zincirleri ve yedek parça toptancıları için set bazında fiyatlandırma ve düzenli tedarik programı sunuyoruz.",
        hashtags="moto", blog="Motosiklet marka-model tekerlek rulmanı ölçü tablosu (26 marka)",
    ),
    dict(
        gun=21, tarih="11 Eki 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="7565159.jpg", etiket="PAZAR NOTU",
        baslik="“Kalite,<br>duyulmayan sestir.”",
        alt="Doğru rulman, doğru montaj, sessiz makine.",
        kw="kaliteli rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar2",
        alt_text="Karanlık zeminde kam mili fotoğrafı; alıntı: Kalite, duyulmayan sestir",
        ig="Kalite, duyulmayan sestir.\n\nİyi pazarlar. Yeni hafta sanayi tipi rulmanlarla başlıyor.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=22, tarih="12 Eki 2026 Pzt", platform="IG, FB, LI", pillar="Ürün",
        sablon="split", foto="2760241.jpg", etiket="SANAYİ",
        baslik="KONİK.<br>SİLİNDİRİK.<br>OYNAK.",
        alt="Redüktör, konveyör, pompa ve tezgâhlar için makaralı ve oynak bilyalı rulmanlar.",
        kw="konik makaralı rulman, silindirik makaralı rulman, oynak bilyalı rulman",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=sanayi",
        alt_text="Fabrikada büyük vidalı mil önünde mühendis; sanayi tipi konik, silindirik ve oynak rulmanlar",
        ig="Sadece motosiklet değil. Sanayi tarafında da 1986'dan beri buradayız.\n\n• Konik makaralı (30200/30300/32000 serileri)\n• Silindirik makaralı (NU/NJ/N serileri)\n• Oynak bilyalı (1200/2200 serileri)\n• Geniş kesitli ve yataklı (UCP/UCF) rulmanlar\n\nRedüktör, konveyör, pompa, tezgâh. Ölçü ve kodunuzu yazın.",
        li="Sanayi uygulamalarında rulman seçimi yük tipiyle başlar: radyal yük için silindirik makaralı (NU, NJ), birleşik yük için konik makaralı (30200/30300), eksen kaçıklığı olan uzun millerde oynak bilyalı (1200/2200) rulmanlar.\n\nYamansa, bu ailelerin tümünü SKF, FAG ve ORS markalarıyla stoklamaktadır. Bakım planlaması yapan ekipler için kritik yedek listesi oluşturma desteği veriyoruz.",
        hashtags="sanayi", blog="Konik, silindirik ve oynak rulman: hangi yükte hangisi?",
    ),
    dict(
        gun=23, tarih="13 Eki 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="İNCE KESİT",
        baslik="6800 / 6900<br>İNCE KESİT",
        alt="E-scooter, drone, bisiklet ve robotik için dar alan rulmanları.",
        tablo=[("6800", "10 × 19 × 5"), ("6801", "12 × 21 × 5"), ("6802", "15 × 24 × 5"),
               ("6900", "10 × 22 × 6"), ("6901", "12 × 24 × 6"), ("6902", "15 × 28 × 7")],
        kw="6900 rulman, 6800 rulman, ince kesit rulman, 61900 rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=ince-kesit",
        alt_text="6800 ve 6900 serisi ince kesit rulman ölçü tablosu",
        ig="Dar alan, hafif yük, yüksek devir: 6800 ve 6900 serileri.\n\n6800 → 10×19×5\n6801 → 12×21×5\n6802 → 15×24×5\n6900 → 10×22×6\n6901 → 12×24×6\n6902 → 15×28×7\n\nE-scooter tekerlekleri, drone motorları, bisiklet göbekleri. NMB ve TPI seçenekleriyle stokta.",
        hashtags="scooter", blog="İnce kesit rulmanlar: 6700/6800/6900 serileri ölçü tablosu",
    ),
    dict(
        gun=24, tarih="14 Eki 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="istatistik", foto="4483608.jpg", etiket="STOK GÖRÜNÜRLÜĞÜ",
        baslik="STOK, HER GÜN<br>GÜNCELLENİR.",
        alt="Sitede gördüğünüz stok gerçek stok. Telefon açıp sormanıza gerek kalmaz.",
        sayilar=[("1986", "kuruluş yılı"), ("6", "distribütör marka"), ("26", "motosiklet & scooter markası"), ("15:00", "aynı gün kargo sınırı")],
        kw="rulman stok sorgulama, online rulman satış, rulman fiyat listesi",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=stok",
        alt_text="Depo rafları koridoru; Yamansa rakamlarla: 1986, 6 marka, 26 marka, 15:00 kargo",
        ig="\"Var mı?\" diye aramanıza gerek yok.\n\nyamansarulman.com'da gördüğünüz stok, o günün gerçek stoğu. Her sabah güncellenir. Ölçü filtresiyle iç çap / dış çap / kalınlık girin, stoktaki tüm markaları yan yana görün.\n\n1986'dan beri • 6 distribütör marka • 26 araç markası • 15:00'e kadar aynı gün kargo",
        li="B2B e-ticarette en büyük güven sorunu stok bilgisinin gerçek olmamasıdır. Yamansa'da ürün sayfalarındaki stok her gün otomatik olarak güncellenir; satın alma ekipleri telefonla doğrulama yapmak zorunda kalmaz.\n\nÖlçü tabanlı filtreleme (iç çap / dış çap / kalınlık) ile kod bilmeden doğru rulmana ulaşılır. Kurumsal müşteriler için fiyat listesi ve cari hesap seçenekleri mevcuttur.",
        hashtags="sanayi", blog="",
    ),
    dict(
        gun=25, tarih="15 Eki 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="28231807.jpg", etiket="3 ADIM",
        baslik="KUMPASLA<br>RULMAN ÖLÇÜMÜ",
        alt="Kod okunmuyorsa üç ölçü yeter.",
        liste=["İç çap (d): mile oturan deliği ölç", "Dış çap (D): en geniş dış kenarı ölç", "Kalınlık (B): bileziğin genişliğini ölç",
               "Kapak tipine bak: metal (ZZ) / kauçuk (2RS)"],
        kw="rulman ölçüsü nasıl alınır, kumpasla rulman ölçme, rulman iç çap dış çap",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=kumpas",
        alt_text="Kumpasla ölçüm yapılan atölye masası; kumpasla rulman ölçümü 3 adım listesi",
        ig="Kod silindi, rulman elimde: ne yapayım?\n\n1. İç çap (d) – mile oturan deliği ölç\n2. Dış çap (D) – dış kenarı ölç\n3. Kalınlık (B) – bilezik genişliğini ölç\n+ Kapak tipine bak: metal mi kauçuk mu?\n\n20 × 47 × 14 + kauçuk → 6204-2RS. Ölçüleri yaz, kodunu ve fiyatını gönderelim.",
        hashtags="teknik", blog="Kumpasla rulman ölçümü ve ölçüden kod bulma tablosu",
    ),
    dict(
        gun=26, tarih="16 Eki 2026 Cum", platform="IG, FB", pillar="Teknik",
        sablon="karsilastirma", foto="19911427.jpg", etiket="SIK SORULAN",
        baslik="6204 MÜ,<br>6304 MÜ?",
        alt="Aynı iç çap (20 mm), farklı kesit. Yuvaya bak, karar ver.",
        sol=("6204", "20 × 47 × 14", ["Standart kesit", "Yüksek devir", "Motor, pompa, fan", "Daha ekonomik"]),
        sag=("6304", "20 × 52 × 15", ["Kalın kesit", "Yüksek yük", "Tekerlek, tarım, redüktör", "Daha uzun ömür (ağır yük)"]),
        kw="6204 6304 farkı, 6204 rulman ölçüsü, 6304 rulman ölçüsü",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=6204-6304",
        alt_text="6204 ve 6304 rulman karşılaştırma tablosu",
        ig="6204 mü 6304 mü? İkisi de 20 mm iç çap; fark dış çapta ve yük kapasitesinde.\n\n6204 → 20×47×14 – standart kesit, yüksek devir, motor/pompa/fan\n6304 → 20×52×15 – kalın kesit, ağır yük, tekerlek/tarım/redüktör\n\nKural: Yuva ölçüsü neyse o. 47 mm yuvaya 6304 girmez; 52 mm yuvada 6204 döner ama tutmaz. Ölçüyü yaz, karar verelim.",
        hashtags="teknik", blog="6204 ve 6304 farkı: ölçü, yük ve kullanım alanı",
    ),
    dict(
        gun=27, tarih="17 Eki 2026 Cmt", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="split", foto="32845661.jpg", etiket="TEKNİK DESTEK",
        baslik="ÖLÇÜ. MUADİL.<br>MARKA<br>ÖNERİSİ.",
        alt="Kodunuzun muadilini, uygun marka ve kapak tipini birlikte belirleyelim. Ücretsiz.",
        kw="rulman muadil bulma, rulman teknik destek, rulman danışmanlık",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=teknik-destek",
        alt_text="CNC tezgâh başında mavi iş kıyafetli mühendis; Yamansa teknik destek",
        ig="Elinizdeki kod eski bir katalogdan mı? Üretimden kalkmış bir marka mı?\n\nEkibimiz muadil kodu, uygun markayı ve doğru kapak/boşluk tipini birlikte belirler. 40 yıla yakın tecrübe, ücretsiz.\n\nDM, WhatsApp veya 0552 610 93 63.",
        li="Bakım ekiplerinin sık karşılaştığı sorun: eski makinelerde üretimi durmuş ya da farklı standartta kodlanmış rulmanlar. Bu durumda doğru muadili bulmak, makinenin ömrünü belirler.\n\nYamansa teknik ekibi; ölçü doğrulama, muadil kod tespiti, marka ve boşluk sınıfı önerisini ücretsiz sunar. 1986'dan beri biriken saha tecrübesi, hızlı ve doğru karar için en güçlü aracımız.",
        hashtags="sanayi", blog="Rulman muadil tablosu: eski kodlardan yeni standarda geçiş",
    ),
    dict(
        gun=28, tarih="18 Eki 2026 Paz", platform="IG, FB", pillar="CTA",
        sablon="hero", foto="10294593.jpg", etiket="HAFTA SONU",
        baslik="ÖN + ARKA SET,<br>KARGO BİZDEN.",
        alt="Motosiklet ve scooter tekerlek rulmanı setlerinde bu hafta kargo ücretsiz. (Öneri – onayınıza bağlı)",
        kw="motosiklet rulman seti, ücretsiz kargo rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=set-kampanya",
        alt_text="Turuncu motosiklet jantı ve jant telleri; ön ve arka tekerlek rulman seti kampanyası",
        ig="Bu hafta motosiklet ve scooter tekerlek rulmanı setlerinde kargo bizden.\n\nÖn + arka seti birlikte al, ücretsiz kargoyla aynı gün yola çıksın. Marka + model yaz, set fiyatını gönderelim.\n\nKampanya 25 Ekim'e kadar geçerlidir.",
        hashtags="moto", blog="",
    ),
    dict(
        gun=29, tarih="19 Eki 2026 Pzt", platform="IG, FB, LI", pillar="Marka",
        sablon="istatistik", foto="29224559.jpg", etiket="1986 → 2026",
        baslik="40 YILA YAKIN<br>TECRÜBE.",
        alt="Üç kuşak rulmancı. Aynı adres, aynı ilke: doğru ürün, doğru fiyat, zamanında teslim.",
        sayilar=[("1986", "İkitelli'de kuruluş"), ("6", "distribütör marka"), ("3", "rulman ailesi: bilyalı, makaralı, oynak"), ("81", "ile aynı gün sevkiyat")],
        kw="rulman firması istanbul, köklü rulman tedarikçisi, yamansa rulman hakkında",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=40yil",
        alt_text="Fabrika üretim hattında çalışanlar; Yamansa 1986'dan 2026'ya rakamlar",
        ig="1986'da İkitelli'de küçük bir dükkânla başladı. Bugün 81 ile aynı gün sevkiyat yapan bir rulman tedarikçisiyiz.\n\nDeğişmeyen tek şey ilkemiz: doğru ürün, doğru fiyat, zamanında teslim.\n\nBizi takip ettiğiniz için teşekkürler.",
        li="Yamansa Rulman 1986'da İkitelli'de kuruldu. 40 yıla yaklaşan sürede rulman ithalatı ve distribütörlüğünde uzmanlaştık; kendi alanında uzman üreticilerin yeni nesil rulmanlarını Türkiye pazarına sunduk.\n\nBugün SKF, FAG, ORS, NMB, TPI ve Yamansa markalı ürünlerle sanayi, motosiklet ve mikro mobilite sektörlerine hizmet veriyoruz. Yeni dönemde dijital stok görünürlüğü ve B2B çevrimiçi sipariş ile büyümeye devam ediyoruz.",
        hashtags="genel", blog="Yamansa Rulman hikâyesi: 1986'dan bugüne",
    ),
    dict(
        gun=30, tarih="20 Eki 2026 Sal", platform="IG, FB, LI", pillar="CTA",
        sablon="hero", foto="19911421.jpg", etiket="KATALOG",
        baslik="ÖLÇÜNÜ GİR,<br>RULMANINI BUL.",
        alt="İç çap / dış çap / kalınlık filtresiyle tüm markaları yan yana karşılaştır. yamansarulman.com",
        kw="online rulman katalog, rulman ölçü filtresi, rulman satın al",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=katalog",
        alt_text="Çelik rulman bilezikleri ve bilyeler; Yamansa online katalog çağrısı",
        ig="Bir aydır anlattık: kod okuma, ZZ/2RS, C3, ölçü alma, montaj…\n\nŞimdi sıra sizde: yamansarulman.com'a gir, ölçünü yaz, stoktaki tüm markaları fiyatıyla gör. Saat 15:00'e kadar sipariş, aynı gün kargo.\n\nKaçırdığınız gönderiler için profilimize göz atın. Sorularınız için DM her zaman açık. Yarın 2. ay başlıyor: kapak kodları, konik rulmanlar, 608, çamaşır makinesi rulmanı ve daha fazlası.",
        li="Bir aylık içerik serimizde rulman kodlarını, kapak ve boşluk sınıflarını, ölçü almayı ve montaj hatalarını ele aldık. Tüm içeriklere sayfamızdan ulaşabilirsiniz.\n\nÖlçü tabanlı çevrimiçi kataloğumuz yamansarulman.com adresinde: iç çap / dış çap / kalınlık girin, stoktaki markaları karşılaştırın. Kurumsal tedarik için ekibimizle iletişime geçin.",
        hashtags="genel", blog="Site içi arama ve ölçü filtresi kullanım rehberi",
    ),
    # ------------------------------------------------------------------ 2. AY (Gün 31–60)
    dict(
        gun=31, tarih="21 Eki 2026 Çar", platform="IG, FB, LI", pillar="Teknik",
        sablon="bilgi", foto="19911427.jpg", etiket="KAPAK KODLARI",
        baslik="Z, ZZ, RS, 2RS, 2RZ<br>NE DEMEK?",
        alt="Kod sonundaki harfler kapak ve keçe tipini söyler.",
        liste=["Z / ZZ (2Z) – Tek / çift taraf metal kapak", "RS / 2RS (2RS1, DDU) – Tek / çift taraf temaslı kauçuk keçe",
               "2RZ (2RSL) – Temassız kauçuk keçe: düşük sürtünme + toz koruması", "Harf yoksa – Açık rulman: harici yağlama ister"],
        kw="2rz rulman ne demek, z rulman zz rulman farkı, rs rulman, 2rs1 ddu",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=kapak-kodlari",
        alt_text="Bilyalı rulman fotoğrafı üzerinde Z, ZZ, RS, 2RS ve 2RZ kapak kodlarının açıklaması",
        ig="2. aya teknikle başlıyoruz: kod sonundaki harfler ne diyor?\n\nZ / ZZ → tek / çift metal kapak\nRS / 2RS → tek / çift kauçuk keçe (SKF'de 2RS1, NSK'de DDU)\n2RZ → temassız keçe: ZZ'nin düşük sürtünmesi + kauçuğun toz koruması\nHarf yok → açık rulman, yağlamayı siz yaparsınız\n\nKaydet; ölçünüzü yazarken harfleri de yazın, tam eşleşme gönderelim.",
        li="Rulman kodlarındaki kapak ekleri markadan markaya değişir ve satın almada sık karışıklık yaratır: SKF 2RS1 / 2RZ, NSK DDU / VV, FAG 2RSR / 2HRS aynı işlevi karşılar.\n\nTemaslı keçe (2RS) en yüksek korumayı, metal kapak (ZZ) en düşük sürtünmeyi, temassız keçe (2RZ) ikisinin arasını verir. Muadil seçerken yalnızca ölçü değil, kapak tipi de eşleşmelidir.\n\nMarkalar arası muadil tablomuz için ekibimizle iletişime geçebilirsiniz.",
        hashtags="teknik", blog="Rulman kapak kodları: Z, ZZ, RS, 2RS, 2RZ ve marka karşılıkları (SKF, NSK, FAG)",
    ),
    dict(
        gun=32, tarih="22 Eki 2026 Per", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6200 • BÜYÜK",
        baslik="6206 – 6211<br>BÜYÜK ÖLÇÜLER",
        alt="Çamaşır makinesi, pompa, tarım ve redüktör: 6200 serisinin büyük kardeşleri.",
        tablo=[("6206", "30 × 62 × 16"), ("6207", "35 × 72 × 17"), ("6208", "40 × 80 × 18"),
               ("6209", "45 × 85 × 19"), ("6210", "50 × 90 × 20"), ("6211", "55 × 100 × 21")],
        kw="6206 rulman, 6207 rulman, 6208 rulman, 6210 rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6200-buyuk",
        alt_text="6206'dan 6211'e 6200 serisi büyük ölçü rulman tablosu",
        ig="6200 serisinin devamı: 30 mm'den 55 mm iç çapa.\n\n6206 → 30×62×16\n6207 → 35×72×17\n6208 → 40×80×18\n6209 → 45×85×19\n6210 → 50×90×20\n6211 → 55×100×21\n\nÇamaşır makinesi, su pompası, tarım makinesi, redüktör. ZZ, 2RS ve C3 seçenekleriyle stokta.",
        hashtags="genel", blog="6206, 6207, 6208, 6209, 6210 rulman ölçüleri ve kullanım alanları",
    ),
    dict(
        gun=33, tarih="23 Eki 2026 Cum", platform="IG, FB, LI", pillar="Uygulama",
        sablon="hero", foto="34397245.jpg", etiket="BEYAZ EŞYA",
        baslik="ÇAMAŞIR MAKİNESİ<br>RULMANI.",
        alt="Sıkmada uçak gibi ses mi geliyor? Kazan rulmanı bitmiştir. 6204, 6205, 6206, 6305, 6306 stokta.",
        kw="çamaşır makinesi rulmanı, çamaşır makinesi rulman ölçüsü, 6205 6206 rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=camasir-makinesi",
        alt_text="Paslanmaz çamaşır makinesi kazanı yakın çekim üzerinde 'Çamaşır makinesi rulmanı' başlığı",
        ig="Sıkma sırasında uçak kalkıyor gibi ses mi geliyor? Kazan rulmanı bitmiş demektir.\n\nÇamaşır makinelerinde en çok kullanılan kodlar:\n• 6204 / 6205 / 6206 (2RS veya ZZ)\n• 6305 / 6306 (ağır hizmet)\n\nMarka ne olursa olsun kodu rulmanın üzerinde yazar; silinmişse üç ölçüyü yaz, biz bulalım. Servisler için toplu fiyat.",
        li="Beyaz eşya servislerinde en yüksek adetli rulman değişimi çamaşır makinesi kazan rulmanlarıdır. Çoğu model 6204–6206 ve 6305–6306 kodlarını kullanır; keçe ile birlikte set olarak değişmesi gerekir.\n\nYamansa olarak bu ölçülerde SKF, FAG, ORS ve Yamansa markalı seçenekleri derin stokla tutuyoruz. Servis zincirleri için aylık çerçeve fiyat sunabiliyoruz.",
        hashtags="beyazesya", blog="Çamaşır makinesi rulmanı ölçüleri: marka-model bazlı 6204/6205/6206/6305/6306 tablosu",
    ),
    dict(
        gun=34, tarih="24 Eki 2026 Cmt", platform="IG, FB", pillar="Uygulama",
        sablon="split", foto="3371219.jpg", etiket="608",
        baslik="608:<br>DÜNYANIN EN ÇOK<br>SATAN RULMANI",
        alt="8 × 22 × 7 mm. Kaykay, paten, scooter, 3D yazıcı, fidget spinner… Hepsinde aynı rulman.",
        kw="608 rulman, 608zz rulman, 608 2rs, kaykay rulmanı, paten rulmanı",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=608",
        alt_text="Kaykay tekerleği ve aksı yakın çekim; 608 rulman tanıtımı",
        ig="Dünyada en çok üretilen rulman kodu: 608.\n\n8 × 22 × 7 mm. Kaykay ve paten tekerleği, e-scooter, 3D yazıcı, drone, fidget spinner…\n\n608ZZ → metal kapak, hızlı ve hafif\n608-2RS → kauçuk keçe, dış ortam\nABEC sınıfı → hassasiyet; 608 ABEC-7 kaykayda tercih edilir\n\nAdetli fiyat için DM. Hafta sonu keyifli sürüşler.",
        hashtags="kaykay", blog="608 rulman nedir? 608ZZ / 608-2RS farkı ve ABEC sınıfları",
    ),
    dict(
        gun=35, tarih="25 Eki 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="20607184.jpg", etiket="PAZAR NOTU",
        baslik="“Dönen her şeyin<br>altında bir rulman vardır.”",
        alt="Görünmez ama vazgeçilmez.",
        kw="rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar3",
        alt_text="CNC tezgâh kesici ucu yakın çekim; alıntı: Dönen her şeyin altında bir rulman vardır",
        ig="Dönen her şeyin altında bir rulman vardır.\n\nİyi pazarlar. Yeni hafta: rulman neden erken biter?",
        hashtags="genel", blog="",
    ),
    dict(
        gun=36, tarih="26 Eki 2026 Pzt", platform="IG, FB, LI", pillar="Teknik",
        sablon="bilgi", foto="asinmis_bilezik_cc0.jpg", etiket="ARIZA ANALİZİ",
        baslik="RULMAN NEDEN<br>ERKEN BİTER?",
        alt="Arızaların büyük çoğunluğu rulmanın kendisinden değil, çevresinden kaynaklanır.",
        liste=["Yetersiz, fazla veya yanlış yağlama", "Kir, toz ve su girişi (yanlış kapak seçimi)", "Montaj hatası: darbe, eğik oturtma",
               "Hizasızlık, aşırı yük veya yanlış boşluk sınıfı", "Sahte / düşük kaliteli ürün"],
        kw="rulman neden bozulur, rulman ömrü, rulman arıza nedenleri, rulman erken bitmesi",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=ariza-analizi",
        alt_text="Yüzeyi çukurlaşmış (pitting) aşınmış rulman bileziği yakın çekim; rulmanın erken bitmesinin 5 nedeni listesi",
        ig="Yeni taktığınız rulman 3 ayda bitti mi? Suçlu genelde rulman değil.\n\n1. Yanlış / yetersiz yağlama\n2. Kir ve su girişi\n3. Montaj hatası\n4. Hizasızlık, aşırı yük, yanlış boşluk sınıfı\n5. Sahte ürün\n\nBitmiş rulmanı atmayın; fotoğrafını DM'den gönderin, iz tipinden nedeni birlikte okuyalım.",
        li="Saha verilerine göre rulman arızalarının yalnızca küçük bir kısmı malzeme yorulmasından kaynaklanır; çoğunluğu yağlama, kirlenme ve montaj hatalarına bağlıdır.\n\nBitmiş rulmanın yüzey izleri (koyu bantlar, pullanma, korozyon lekeleri, kafes deformasyonu) arıza nedenini söyler. Bakım ekipleri için kısa bir arıza analizi rehberi hazırladık; talep eden ekiplere gönderiyoruz.\n\nDoğru teşhis, aynı arızanın tekrarını önler.",
        hashtags="teknik", blog="Rulman arıza analizi: yüzey izlerinden nedeni okumak (yağlama, kirlenme, montaj, hizasızlık)",
    ),
    dict(
        gun=37, tarih="27 Eki 2026 Sal", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="pixabay_3460126.jpg", etiket="KONİK MAKARALI",
        baslik="30200 SERİSİ<br>KONİK RULMAN",
        alt="Radyal + eksenel yükü birlikte taşır. Tekerlek poyrası, redüktör, direksiyon.",
        tablo=[("30203", "17 × 40 × 13,25"), ("30204", "20 × 47 × 15,25"), ("30205", "25 × 52 × 16,25"),
               ("30206", "30 × 62 × 17,25"), ("30207", "35 × 72 × 18,25"), ("30208", "40 × 80 × 19,75")],
        kw="30204 rulman, 30205 rulman, konik makaralı rulman ölçüleri, 30200 serisi",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=konik-30200",
        alt_text="Konik makaralı rulman ürün fotoğrafı ve 30203'ten 30208'e ölçü tablosu",
        ig="Konik makaralı rulman: radyal ve eksenel yükü aynı anda taşır.\n\n30203 → 17×40×13,25\n30204 → 20×47×15,25\n30205 → 25×52×16,25\n30206 → 30×62×17,25\n30207 → 35×72×18,25\n30208 → 40×80×19,75\n\nKonik rulmanlar çift olarak çalışır; ön yük ayarı ömrü belirler. Araç poyrası, redüktör, motosiklet direksiyonu. SKF, FAG, ORS stokta.",
        hashtags="sanayi", blog="30200 / 30300 / 32000 konik makaralı rulman ölçü tablosu ve ön yük ayarı",
    ),
    dict(
        gun=38, tarih="28 Eki 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="bilgi", foto="3862614.jpg", etiket="PLANLI BAKIM",
        baslik="KRİTİK YEDEK<br>LİSTESİ",
        alt="Beklenmedik duruşun ilacı: doğru rulmanı doğru zamanda rafta bulundurmak.",
        liste=["Duruş maliyeti en yüksek makineleri belirle", "Her makinenin rulman kodlarını ve adetlerini çıkar",
               "Tedarik süresi uzun kalemleri rafta tut", "Muadilleri önceden onaylat", "Listeyi yılda bir güncelle"],
        kw="kritik yedek parça listesi, planlı bakım rulman, bakım stoğu",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=kritik-yedek",
        alt_text="Üretim hattı önünde gülümseyen mühendis; kritik yedek listesi 5 adım",
        ig="Makine gece 02:00'de durdu, rulman yok, kargo sabah. Tanıdık mı?\n\nKritik yedek listesi 5 adımda:\n1. Duruşu en pahalı makineleri belirle\n2. Rulman kodlarını ve adetlerini çıkar\n3. Tedariki uzun olanları rafta tut\n4. Muadilleri önceden onaylat\n5. Yılda bir güncelle\n\nListenizi çıkarmada yardımcı oluyoruz; makine listenizi DM'den gönderin.",
        li="Planlı bakımın en ucuz sigortası kritik yedek listesidir. Yüksek duruş maliyetli ekipmanların rulman kodları, adetleri ve onaylı muadilleri tek bir listede tutulmalı; tedarik süresi uzun kalemler rafta bekletilmelidir.\n\nYamansa olarak bakım ekiplerine bu listeyi oluşturmada teknik destek veriyoruz: kod doğrulama, muadil onayı ve stokta tutma önerileri. Yıl sonu bakım duruşları için şimdi doğru zaman.",
        hashtags="sanayi", blog="Kritik yedek parça listesi nasıl hazırlanır? Rulman odaklı planlı bakım rehberi",
    ),
    dict(
        gun=39, tarih="29 Eki 2026 Per", platform="IG, FB, LI", pillar="Marka",
        sablon="hero", foto="29224559.jpg", etiket="29 EKİM 1923",
        baslik="CUMHURİYET<br>BAYRAMIMIZ<br>KUTLU OLSUN.",
        alt="103. yıl. Üreten, çalışan ve dönen bir Türkiye için.",
        kw="",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=29ekim",
        alt_text="Fabrika üretim hattında çalışanlar; Cumhuriyet Bayramı kutlama mesajı",
        ig="Cumhuriyetimizin 103. yılı kutlu olsun.\n\nÜreten, çalışan ve dönen bir Türkiye için; 1986'dan beri İkitelli'den.",
        li="Cumhuriyetimizin 103. yılı kutlu olsun. Üreten ve çalışan Türkiye'nin bir parçası olmaktan gurur duyuyoruz.",
        hashtags="29ekim", blog="",
    ),
    dict(
        gun=40, tarih="30 Eki 2026 Cum", platform="IG, FB", pillar="Teknik",
        sablon="karsilastirma", foto="8956445.jpg", etiket="TEKNİK BİLGİ",
        baslik="BİLYALI MI,<br>MAKARALI MI?",
        alt="Temas şekli her şeyi belirler: nokta mı, çizgi mi?",
        sol=("BİLYALI", "Nokta temas", ["Yüksek devir", "Düşük sürtünme", "Hafif – orta yük", "Ekonomik, yaygın"]),
        sag=("MAKARALI", "Çizgi temas", ["Ağır yük", "Darbeli çalışma", "Daha düşük devir", "Redüktör, konveyör, poyra"]),
        kw="bilyalı rulman makaralı rulman farkı, bilyalı rulman nedir, makaralı rulman nedir",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=bilyali-makarali",
        alt_text="Bilyalı ve makaralı rulman karşılaştırma tablosu",
        ig="Bilyalı mı, makaralı mı?\n\nBilyalı → nokta temas: hızlı döner, az sürter, hafif–orta yük. Motor, fan, tekerlek.\nMakaralı → çizgi temas: çok yük taşır, darbeye dayanır, daha yavaş. Redüktör, konveyör, ağır poyra.\n\nAynı yuvaya ikisi de giriyorsa yük ve devre bakın. Emin değilseniz uygulamayı yazın.",
        hashtags="teknik", blog="Bilyalı ve makaralı rulman farkı: hangi yükte, hangi devirde?",
    ),
    dict(
        gun=41, tarih="31 Eki 2026 Cmt", platform="IG, FB", pillar="Uygulama",
        sablon="split", foto="37811591.jpg", etiket="MOTOSİKLET",
        baslik="DİREKSİYON &<br>SALINCAK<br>RULMANLARI",
        alt="Motosiklette sadece tekerlekte değil: boyun (direksiyon) konik rulmanları ve salıncak rulmanları da stokta.",
        kw="motosiklet direksiyon rulmanı, boyun rulmanı, salıncak rulmanı, motosiklet konik rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=direksiyon-salincak",
        alt_text="Motosiklet ön tekerlek ve fren diski; direksiyon ve salıncak rulmanları tanıtımı",
        ig="Gidon ortada 'takılıyor', virajda kendi kendine düzeliyor mu? Boyun (direksiyon) rulmanı bitmiştir.\n\n• Direksiyon konik rulman setleri (üst + alt)\n• Salıncak rulman ve burç setleri\n• Ön / arka tekerlek setleri\n\nMarka + model yaz, tam seti aynı gün kargolayalım. Kış bakımı için ideal zaman.",
        hashtags="moto", blog="Motosiklet direksiyon (boyun) rulmanı belirtileri ve model bazlı set tablosu",
    ),
    dict(
        gun=42, tarih="1 Kas 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="18500079.jpg", etiket="PAZAR NOTU",
        baslik="“Doğru parça, doğru yerde,<br>doğru zamanda.”",
        alt="Tedarikin üç kuralı. Kasım'a hoş geldiniz.",
        kw="rulman tedarik",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar4",
        alt_text="Paslı çelik bağlantı elemanı yakın çekim; alıntı: Doğru parça, doğru yerde, doğru zamanda",
        ig="Doğru parça, doğru yerde, doğru zamanda.\n\nKasım'a hoş geldiniz. Yarın silindirik makaralı kodlarıyla devam.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=43, tarih="2 Kas 2026 Pzt", platform="IG, FB, LI", pillar="Ürün",
        sablon="bilgi", foto="2760241.jpg", etiket="SİLİNDİRİK",
        baslik="NU, NJ, NUP, N<br>NE DEMEK?",
        alt="Silindirik makaralı rulmanda harfler flanş yerini, yani eksenel tutmayı söyler.",
        liste=["NU – İç bilezik flanşsız: mil eksenel serbest kayar", "NJ – İç bilezikte tek flanş: bir yönde tutar",
               "NUP – Tek flanş + baskı halkası: iki yönde tutar", "N – Dış bilezik flanşsız, iç bilezik flanşlı"],
        kw="nu 205 rulman, silindirik makaralı rulman kodları, nj rulman, nup rulman",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=nu-nj-nup",
        alt_text="Fabrikada büyük vidalı mil önünde işçi; NU, NJ, NUP, N silindirik rulman kodları listesi",
        ig="NU 205 mi, NJ 205 mi? Ölçü aynı, davranış farklı.\n\nNU → iç bilezik flanşsız, mil serbest kayar (ısıl genleşme için)\nNJ → tek flanş, bir yönde tutar\nNUP → flanş + halka, iki yönde tutar\nN → flanşlar iç bilezikte\n\nRedüktör, elektrik motoru, vinç. Kodun tamamını yazın, doğru tipi gönderelim.",
        li="Silindirik makaralı rulman seçiminde ölçü kadar flanş düzeni de kritiktir. NU tipi serbest yatak (ısıl genleşmeyi alır), NJ tek yönlü, NUP çift yönlü sabit yatak olarak kullanılır. Yanlış tip seçimi, mil ekseninde istenmeyen kuvvet birikmesine yol açar.\n\nYamansa olarak NU/NJ/NUP/N serilerini SKF, FAG ve ORS markalarıyla stokluyor; yatak düzeni (sabit–serbest) seçiminde teknik destek veriyoruz.",
        hashtags="sanayi", blog="NU, NJ, NUP, N: silindirik makaralı rulman tipleri ve sabit–serbest yatak düzeni",
    ),
    dict(
        gun=44, tarih="3 Kas 2026 Sal", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="29342768.jpg", etiket="KOD REHBERİ",
        baslik="EK HARFLER<br>NE DEMEK?",
        alt="Aynı ölçü, farklı harf; farklı rulman. En sık görülen ekler:",
        liste=["ZZ / 2RS / 2RZ – Kapak ve keçe tipi", "C3 / C4 – Geniş iç boşluk", "K – Konik delik (manşonla montaj)",
               "N / NR – Dış bilezikte kanal / segman", "TN9 / M / J – Polyamid / pirinç / sac kafes"],
        kw="rulman ek harfleri, rulman son ekleri, rulman k ne demek, tn9 rulman, nr rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=ek-harfler",
        alt_text="Krom motor parçaları yakın çekim; rulman ek harfleri listesi",
        ig="6205 ile 6205-K aynı rulman değil.\n\nZZ / 2RS / 2RZ → kapak–keçe\nC3 / C4 → geniş boşluk\nK → konik delik\nN / NR → dış bilezikte kanal / segman\nTN9 / M / J → polyamid / pirinç / sac kafes\n\nSiparişte kodu harfleriyle birlikte yazın; sonradan 'uymadı' derdi yaşamayın. Kaydet.",
        hashtags="teknik", blog="Rulman kodlarındaki ek harfler (sonekler) sözlüğü: K, N, NR, TN9, M, E, C3",
    ),
    dict(
        gun=45, tarih="4 Kas 2026 Çar", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="split", foto="4480986.jpg", etiket="KURUMSAL",
        baslik="CARİ HESAP.<br>TEK FATURA.<br>DÜZENLİ SEVK.",
        alt="Fabrika satın alma birimleri ve servis zincirleri için çerçeve anlaşma ve aylık toplu faturalama.",
        kw="kurumsal rulman tedariki, rulman fiyat listesi, rulman cari hesap, rulman çerçeve anlaşma",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=kurumsal",
        alt_text="Depoda görüşen üç kişi; kurumsal rulman tedariki: cari hesap, tek fatura, düzenli sevkiyat",
        ig="Her rulman için ayrı sipariş, ayrı fatura, ayrı takip… Yormuyor mu?\n\nKurumsal müşterilerimize:\n• Cari hesap ve vade\n• Aylık tek fatura\n• Sık kullanılan kodlar için sabit fiyat listesi\n• Haftalık / aylık düzenli sevkiyat\n\nSatın alma ekibinizle 15 dakikalık görüşme için DM veya 0552 610 93 63.",
        li="Satın alma birimleri için rulman tedarikinde asıl maliyet, işlem sayısıdır. Yamansa kurumsal programı bu yükü azaltmak için tasarlandı: cari hesap ve vade, aylık tek fatura, sık kullanılan kodlar için 6 ay sabit fiyat listesi ve planlı sevkiyat.\n\n1986'dan beri sanayi ve servis sektörüne tedarik yapıyoruz. Çerçeve anlaşma görüşmesi için mesaj gönderebilirsiniz.",
        hashtags="sanayi", blog="Kurumsal rulman tedariki: çerçeve anlaşma ve sabit fiyat listesi nasıl işler?",
    ),
    dict(
        gun=46, tarih="5 Kas 2026 Per", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="18845071.jpg", etiket="SÖKME",
        baslik="RULMANI<br>DOĞRU SÖKMEK",
        alt="Yanlış sökme, mili ve yuvayı da bozar. Yeni rulman eğri yuvaya oturmaz.",
        liste=["Çektirme kullan; çekiç ve keski kullanma", "Kuvveti sıkı geçme yapılmış bilezikten uygula",
               "Isıtma gerekiyorsa kontrollü (indüksiyon), alevle değil", "Sökümden sonra mil ve yuvayı ölç, temizle", "Bitmiş rulmanı incele: arıza nedenini söyler"],
        kw="rulman sökme, rulman çektirme, rulman nasıl sökülür, rulman söküm yöntemleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=sokme",
        alt_text="Usta elleri mil üzerinde çalışıyor; rulmanı doğru sökme 5 adım",
        ig="Montaj kadar sökme de önemli. Yanlış sökülen rulman, mili ve yuvayı da götürür.\n\n1. Çektirme kullan; çekiç–keski yok\n2. Kuvveti sıkı geçme bilezikten uygula\n3. Isıtma gerekirse kontrollü, alevle değil\n4. Sonra mil ve yuvayı ölç, temizle\n5. Bitmiş rulmanı atmadan incele\n\nYeni rulman eğri yuvaya oturmaz. Kaydet, ustana gönder.",
        hashtags="teknik", blog="Rulman sökme yöntemleri: çektirme, hidrolik ve ısıl söküm",
    ),
    dict(
        gun=47, tarih="6 Kas 2026 Cum", platform="IG, FB, LI", pillar="Uygulama",
        sablon="split", foto="26860251.jpg", etiket="E-SCOOTER",
        baslik="PAYLAŞIMLI<br>SCOOTER<br>FİLOLARI",
        alt="Filo operatörleri için tekerlek ve motor rulmanlarında adetli tedarik; model bazlı set ve düzenli sevkiyat.",
        kw="scooter filo yedek parça, scooter motor rulmanı, paylaşımlı scooter bakım, scooter tekerlek rulmanı",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=scooter-filo",
        alt_text="Ağaç altında sıralanmış paylaşımlı kırmızı e-scooterlar; filo rulman tedariki",
        ig="Bir scooter filosunda en sık değişen parça ne? Lastikten sonra rulman.\n\nFilo ve servis operatörleri için:\n• Model bazlı tekerlek + motor rulman setleri\n• İnce kesit 6800/6900 ve 6000 serisi derin stok\n• Aylık düzenli sevkiyat, sabit fiyat\n\nFilo büyüklüğünüzü yazın, teklif gönderelim.",
        li="Paylaşımlı mikro mobilite filolarında araç başına bakım maliyetinin önemli kısmı tekerlek ve motor rulmanlarından gelir; yoğun kullanım ve dış ortam rulman ömrünü kısaltır.\n\nYamansa olarak filo operatörlerine model bazlı rulman setleri, 6800/6900/6000 serilerinde derin stok ve aylık planlı sevkiyat sunuyoruz. NMB, TPI ve Yamansa markalı seçeneklerle maliyet–ömür dengesini birlikte kuruyoruz.",
        hashtags="scooter", blog="Paylaşımlı scooter filolarında rulman bakımı ve tedarik planı",
    ),
    dict(
        gun=48, tarih="7 Kas 2026 Cmt", platform="IG, FB", pillar="Marka",
        sablon="bilgi", foto="1595485.jpg", etiket="HAFTA SONU",
        baslik="BUNLARI<br>BİLİYOR MUYDUNUZ?",
        alt="Rulman hakkında 5 kısa bilgi.",
        liste=["Leonardo da Vinci 1500'lerde bilyalı yatak çizmişti", "İlk bilyalı rulman patenti 1794, İngiltere",
               "Modern sabit bilyalı rulman 1869'da bir bisiklet için tasarlandı", "608, dünyada en çok üretilen rulman kodudur",
               "Fidget spinner'ın içinde de bir 608 döner"],
        kw="rulman tarihi, rulmanı kim icat etti, rulman hakkında bilgiler",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=biliyor-muydunuz",
        alt_text="Bisiklet ön tekerlek göbeği ve jant telleri; rulman hakkında 5 ilginç bilgi listesi",
        ig="Hafta sonu bilgi yarışması: rulman hakkında bunları biliyor muydunuz?\n\n1. Leonardo da Vinci 1500'lerde bilyalı yatak çizmişti\n2. İlk bilyalı rulman patenti 1794\n3. Modern sabit bilyalı rulman 1869'da bir bisiklet için tasarlandı\n4. 608, dünyada en çok üretilen kod\n5. Fidget spinner'ın kalbinde de bir 608 var\n\nHangisini bilmiyordunuz? Yoruma yazın.",
        hashtags="genel", blog="Rulmanın tarihi: da Vinci'den 608'e",
    ),
    dict(
        gun=49, tarih="8 Kas 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="30866489.jpg", etiket="PAZAR NOTU",
        baslik="“Sürtünme kaybettirir,<br>rulman kazandırır.”",
        alt="Enerji, zaman, para.",
        kw="rulman enerji verimliliği",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar5",
        alt_text="Motosiklet motoru yakın çekim; alıntı: Sürtünme kaybettirir, rulman kazandırır",
        ig="Sürtünme kaybettirir, rulman kazandırır.\n\nİyi pazarlar. Yarın oynak bilyalı rulmanlar.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=50, tarih="9 Kas 2026 Pzt", platform="IG, FB, LI", pillar="Ürün",
        sablon="urun", foto="19911427.jpg", etiket="OYNAK BİLYALI",
        baslik="1200 SERİSİ<br>OYNAK BİLYALI",
        alt="Eksen kaçıklığını affeder. Uzun miller, tarım, konveyör, tekstil.",
        tablo=[("1200", "10 × 30 × 9"), ("1201", "12 × 32 × 10"), ("1202", "15 × 35 × 11"),
               ("1203", "17 × 40 × 12"), ("1204", "20 × 47 × 14"), ("1205", "25 × 52 × 15")],
        kw="oynak bilyalı rulman, 1204 rulman, 1205 rulman, 2205 rulman, 1200 serisi",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=oynak-1200",
        alt_text="1200'den 1205'e oynak bilyalı rulman ölçü tablosu",
        ig="Mil hizasız mı? Sabit bilyalı bir ayda biter; oynak bilyalı affeder.\n\n1200 → 10×30×9\n1201 → 12×32×10\n1202 → 15×35×11\n1203 → 17×40×12\n1204 → 20×47×14\n1205 → 25×52×15\n\nDış çapları 6200 serisiyle aynı; iki sıra bilya ve küresel dış yuvarlanma yolu var. 2200 serisi (geniş) ve K (konik delik) seçenekleri de stokta.",
        li="Uzun miller, kaynaklı yataklar ve tarım/konveyör uygulamalarında eksen kaçıklığı kaçınılmazdır. Oynak bilyalı rulmanlar (1200/1300/2200/2300 serileri) küresel dış yuvarlanma yoluyla birkaç derece açısal kaçıklığı tolere eder.\n\nDış ölçüleri 6200/6300 serileriyle aynı olduğu için mevcut yuvaya doğrudan uygulanabilir. Konik delikli (K) tipler manşonla montaj kolaylığı sağlar. SKF, FAG ve ORS seçenekleriyle stokta.",
        hashtags="sanayi", blog="Oynak bilyalı rulman nedir? 1200/2200 serisi ölçüleri ve konik delik (K) montajı",
    ),
    dict(
        gun=51, tarih="10 Kas 2026 Sal", platform="IG, FB, LI", pillar="Marka",
        sablon="alinti", foto="34718930.jpg", etiket="10 KASIM",
        baslik="Saygı, sevgi ve<br>minnetle anıyoruz.",
        alt="Mustafa Kemal Atatürk · 1881 – 1938",
        kw="",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=10kasim",
        alt_text="Boş fabrika koridoru siyah-beyaz; 10 Kasım anma mesajı",
        ig="Cumhuriyetimizin kurucusu Gazi Mustafa Kemal Atatürk'ü saygı, sevgi ve minnetle anıyoruz.\n\n10 Kasım 1938",
        li="Cumhuriyetimizin kurucusu Gazi Mustafa Kemal Atatürk'ü aramızdan ayrılışının 88. yılında saygı, sevgi ve minnetle anıyoruz.",
        hashtags="10kasim", blog="",
    ),
    dict(
        gun=52, tarih="11 Kas 2026 Çar", platform="IG, FB", pillar="Teknik",
        sablon="karsilastirma", foto="35568191.jpg", etiket="TEKNİK BİLGİ",
        baslik="AÇIK MI,<br>KAPAKLI MI?",
        alt="Yağlamayı kim yapacak: siz mi, fabrika mı?",
        sol=("AÇIK", "Kapaksız", ["Harici yağlama gerekir", "En yüksek devir", "Yağ banyosu, dişli kutusu", "Temiz ve kapalı yuva"]),
        sag=("KAPAKLI", "ZZ / 2RS", ["Ömür boyu gresli", "Bakım gerektirmez", "Toz ve su koruması", "Tekerlek, motor, fan"]),
        kw="açık rulman kapaklı rulman farkı, açık rulman yağlama, açık rulman nedir",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=acik-kapakli",
        alt_text="Açık ve kapaklı rulman karşılaştırma tablosu",
        ig="Açık mı, kapaklı mı?\n\nAçık → yağlamayı sistem yapar (yağ banyosu, dişli kutusu); en yüksek devir; yuva temiz ve kapalı olmalı.\nKapaklı (ZZ/2RS) → fabrikadan gresli gelir, bakım istemez; tekerlek, motor, fan.\n\nKural: Yuvada yağ dolaşımı varsa açık, yoksa kapaklı. Uygulamanızı yazın, seçelim.",
        hashtags="teknik", blog="Açık rulman ve kapaklı rulman farkı: yağlama, devir ve kullanım alanı",
    ),
    dict(
        gun=53, tarih="12 Kas 2026 Per", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="bilgi", foto="19911421.jpg", etiket="ORİJİNAL ÜRÜN",
        baslik="SAHTE RULMANA<br>KARŞI 5 KONTROL",
        alt="Sahte rulman ucuz değildir; makineyle birlikte bitince pahalıdır.",
        liste=["Fiyat piyasanın çok altındaysa şüphelen", "Lazer markalama net, düzgün ve eşit derinlikte olmalı",
               "Kutu, hologram ve parti numarasını kontrol et", "Yetkili kanaldan, faturalı al", "Emin değilsen bize getir; yan yana karşılaştıralım"],
        kw="sahte rulman nasıl anlaşılır, orijinal skf rulman kontrol, sahte skf rulman, orijinal rulman",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=sahte-rulman",
        alt_text="Parlak bilyalı rulmanlar ve bilezikler; sahte rulmana karşı 5 kontrol listesi",
        ig="Sahte rulman ucuz değildir; makineyle birlikte bitince pahalıdır.\n\n1. Fiyat piyasanın çok altındaysa şüphelen\n2. Lazer markalama net ve eşit derinlikte olmalı\n3. Kutu, hologram, parti numarası\n4. Yetkili kanaldan, faturalı al\n5. Emin değilsen bize getir, yan yana bakalım\n\n1986'dan beri yalnızca yetkili kanaldan tedarik. SKF, FAG, ORS, NMB, TPI.",
        li="Sahte rulman, sektörün en büyük görünmez maliyetidir: gerçek malzeme ve ısıl işlem standardını taşımayan ürünler, planlanan ömrün küçük bir kısmında bozulur ve mil, yuva, hatta redüktörü birlikte götürür.\n\nKontrol noktaları: fiyat, lazer markalama kalitesi, ambalaj ve parti numarası, tedarik kanalı. Yamansa, 1986'dan beri yalnızca yetkili distribütör kanallarından tedarik eder ve her ürünü faturalandırır. Şüpheli ürünlerinizi karşılaştırma için getirebilirsiniz.",
        hashtags="sanayi", blog="Sahte rulman nasıl anlaşılır? SKF, FAG, ORS orijinallik kontrol rehberi",
    ),
    dict(
        gun=54, tarih="13 Kas 2026 Cum", platform="IG, FB", pillar="Ürün",
        sablon="urun", foto="19911421.jpg", etiket="SERİ 6300 • BÜYÜK",
        baslik="6306 – 6311<br>AĞIR HİZMET",
        alt="Redüktör, vinç, tarım, kompresör. 6300 serisinin büyük ölçüleri.",
        tablo=[("6306", "30 × 72 × 19"), ("6307", "35 × 80 × 21"), ("6308", "40 × 90 × 23"),
               ("6309", "45 × 100 × 25"), ("6310", "50 × 110 × 27"), ("6311", "55 × 120 × 29")],
        kw="6306 rulman, 6308 rulman, 6310 rulman, 6300 serisi rulman ölçüleri",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=seri6300-buyuk",
        alt_text="6306'dan 6311'e 6300 serisi büyük ölçü rulman tablosu",
        ig="6300 serisinin ağır hizmet ölçüleri:\n\n6306 → 30×72×19\n6307 → 35×80×21\n6308 → 40×90×23\n6309 → 45×100×25\n6310 → 50×110×27\n6311 → 55×120×29\n\nRedüktör, vinç, kompresör, tarım makinesi. C3 ve ZZ/2RS seçenekleriyle; SKF, FAG, ORS stokta.",
        hashtags="sanayi", blog="6306, 6307, 6308, 6309, 6310 rulman ölçüleri ve muadilleri",
    ),
    dict(
        gun=55, tarih="14 Kas 2026 Cmt", platform="IG, FB", pillar="Uygulama",
        sablon="split", foto="34194564.jpg", etiket="ELEKTRİK MOTORU",
        baslik="ELEKTRİK<br>MOTORU<br>RULMANLARI",
        alt="6201'den 6312'ye, ZZ ve C3: motor sarımcıları ve bakım ekipleri için en çok dönen kodlar stokta.",
        kw="elektrik motoru rulmanı, motor rulmanı değişimi, 6205 zz c3, motor sarım rulman",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=elektrik-motoru",
        alt_text="Atölye tezgâhında redüktörlü elektrik motoru; elektrik motoru rulmanları",
        ig="Motor sarımcıları bilir: sarım biter, iş rulmanda biter.\n\nElektrik motorlarında en çok dönen kodlar: 6201–6212 ve 6301–6312, ZZ kapaklı, C3 boşluklu.\n\nNeden ZZ? Kuru ve temiz ortam, yüksek devir.\nNeden C3? Mil ısınır ve genleşir; normal boşluk sıkışır.\n\nMotor etiketindeki gücü ve rulman kodunu yaz, setini gönderelim.",
        hashtags="teknik", blog="Elektrik motoru rulmanı seçimi: neden ZZ ve C3? Güce göre rulman kodu tablosu",
    ),
    dict(
        gun=56, tarih="15 Kas 2026 Paz", platform="IG, FB", pillar="Marka",
        sablon="alinti", foto="14522449.jpg", etiket="PAZAR NOTU",
        baslik="“Bakım masraf değil,<br>sigortadır.”",
        alt="Planlı duruş, plansız duruştan ucuzdur.",
        kw="planlı bakım",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=pazar6",
        alt_text="Dökme metal makine parçası yakın çekim; alıntı: Bakım masraf değil, sigortadır",
        ig="Bakım masraf değil, sigortadır.\n\nİyi pazarlar. Yarın: yıl sonu bakım duruşu planı.",
        hashtags="genel", blog="",
    ),
    dict(
        gun=57, tarih="16 Kas 2026 Pzt", platform="IG, FB, LI", pillar="Kurumsal",
        sablon="hero", foto="4483608.jpg", etiket="YIL SONU",
        baslik="ARALIK DURUŞU İÇİN<br>LİSTEYİ KASIM'DA<br>KAPATIN.",
        alt="Yıl sonu bakım duruşunda 'stokta yok' sürprizi yaşamayın; rulman listenizi bugünden ayırtın.",
        kw="yıllık bakım duruşu, bakım duruşu yedek parça, yıl sonu bakım planı rulman",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=yil-sonu-durus",
        alt_text="Yüksek raflı depo koridoru; yıl sonu bakım duruşu için rulman planlama çağrısı",
        ig="Aralık bakım duruşu için rulman listeniz hazır mı?\n\nDuruş haftasında herkes aynı kodları arar; ithal kalemlerde bekleme 3–6 haftayı bulur. Listenizi Kasım'da gönderin:\n• Stoktakileri adınıza ayıralım\n• Eksikleri zamanında getirelim\n• Muadilleri önceden onaylayalım\n\nDM veya 0552 610 93 63.",
        li="Yıl sonu bakım duruşlarında en sık yaşanan sorun, aynı haftada tüm sektörün aynı rulman kodlarına yönelmesidir. İthal ve özel kalemlerde tedarik süresi bu dönemde belirgin şekilde uzar.\n\nÖnerimiz: duruş listesini Kasım ortasına kadar kapatmak, stoktaki kalemleri rezerve ettirmek ve tedarik süresi uzun kodlar için muadil onayını önceden almak. Yamansa olarak bu süreci bakım ekipleriyle birlikte yürütüyoruz.",
        hashtags="sanayi", blog="Yıl sonu bakım duruşu planlaması: rulman listesi ve tedarik takvimi",
    ),
    dict(
        gun=58, tarih="17 Kas 2026 Sal", platform="IG, FB", pillar="Teknik",
        sablon="bilgi", foto="9242171.jpg", etiket="YAĞLAMA",
        baslik="GRES SEÇİMİ:<br>4 KURAL",
        alt="Açık rulmanlarda ömrün yarısı gresin seçiminde ve miktarında gizlidir.",
        liste=["Çoğu uygulama için lityum bazlı çok amaçlı gres yeter", "Yüksek sıcaklıkta (120 °C üzeri) sentetik / poliüre gres",
               "Farklı gresleri asla karıştırma; eskisini temizle", "Boşluğun %30–50'sini doldur; fazlası ısıtır"],
        kw="rulman gresi seçimi, rulman gres miktarı, lityum gres rulman, rulman yağlama",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=gres-secimi",
        alt_text="Tezgâh başında çalışan teknisyen; rulman gres seçimi 4 kural",
        ig="Açık rulman aldınız; hangi gres, ne kadar?\n\n1. Çoğu iş için lityum bazlı çok amaçlı gres\n2. 120 °C üzeri → sentetik / poliüre\n3. Gresleri karıştırma, eskisini temizle\n4. Boşluğun %30–50'si yeter; fazlası ısıtır ve dışarı atar\n\nUygulama sıcaklığı ve devrini yazın, gres tipini birlikte seçelim.",
        hashtags="teknik", blog="Rulman gresi nasıl seçilir? Sıcaklık, devir ve miktar rehberi",
    ),
    dict(
        gun=59, tarih="18 Kas 2026 Çar", platform="IG, FB, LI", pillar="Ürün",
        sablon="split", foto="yatakli_rulman_pd.jpg", etiket="YATAKLI RULMAN",
        baslik="UCP · UCF · UCFL<br>YATAKLI<br>RULMANLAR",
        alt="Konveyör, tarım ve tesis makineleri için hazır yuvalı rulman üniteleri. UC iç rulmanları da ayrıca stokta.",
        kw="ucp 205 rulman, yataklı rulman, ucf 204, uc 206, ucp yatak fiyat",
        link=f"{SITE}/?utm_source=linkedin&utm_medium=social&utm_campaign=yatakli",
        alt_text="Ayaklı (UCP tipi) yataklı rulman ünitesi ürün fotoğrafı; UCP, UCF, UCFL yataklı rulman tanıtımı",
        ig="Mil var, yuva yok mu? Yataklı rulman.\n\nUCP → ayaklı yuva (zemine / şaseye)\nUCF → kare flanşlı (duvara / plakaya)\nUCFL → oval flanşlı (dar yer)\nUC 204–212 → iç rulman, ayrıca stokta\n\nKonveyör, tarım makinesi, tekstil, gıda hattı. Kod veya mil çapını yaz, gönderelim.",
        li="Yataklı rulman üniteleri (UCP, UCF, UCFL, UCT) konveyör, tarım ve tesis makinelerinde en pratik yataklama çözümüdür: yuva ve rulman tek parça gelir, setuskurla mile bağlanır, açısal kaçıklığı tolere eder.\n\nYamansa olarak UCP/UCF/UCFL ünitelerini ve UC 204–212 iç rulmanlarını stoklu tutuyoruz; paslanmaz ve termoplastik yuva seçenekleri için temin süresi veriyoruz.",
        hashtags="sanayi", blog="UCP, UCF, UCFL yataklı rulman tipleri ve UC 204–212 ölçü tablosu",
    ),
    dict(
        gun=60, tarih="19 Kas 2026 Per", platform="IG, FB, LI", pillar="CTA",
        sablon="hero", foto="32845661.jpg", etiket="SORU – CEVAP",
        baslik="SORUNUZ VARSA,<br>CEVABI BİZDE.",
        alt="Kod, ölçü, muadil, marka, montaj: 40 yıla yakın tecrübe bir mesaj uzağınızda.",
        kw="rulman danışmanlık, rulman fiyat sor, rulman teknik destek, rulman whatsapp",
        link=f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=soru-cevap",
        alt_text="CNC tezgâh başında mavi iş kıyafetli mühendis; Yamansa soru-cevap çağrısı",
        ig="2 ay, 60 gönderi: kod okuma, kapak ve boşluk sınıfları, konik ve silindirik rulmanlar, çamaşır makinesinden scooter filosuna…\n\nEn çok sorulan soruları önümüzdeki hafta yanıtlıyoruz. Sorunuzu yoruma ya da DM'e yazın: kod, ölçü, muadil, marka, montaj – ne olursa.\n\nStok ve fiyat: yamansarulman.com · 0552 610 93 63",
        li="İki aylık içerik serimizde rulman seçimi, kodlama, montaj–söküm ve planlı bakım konularını ele aldık. Teşekkürler.\n\nBir sonraki seride sektörden gelen soruları yanıtlayacağız. Bakım, satın alma ve servis ekiplerinden gelen teknik soruları bu gönderinin altında toplayabiliriz.\n\nÖlçü tabanlı katalog ve güncel stok: yamansarulman.com",
        hashtags="genel", blog="Rulman hakkında sık sorulan sorular (SSS) sayfası",
    ),
]

# LinkedIn günlerinde kullanılacak kısa hashtag seti
LI_HASHTAGS = "#rulman #bearings #endüstri #tedarikzinciri #bakım"


# ============================================================================
# GÜNLÜK 3 PAYLAŞIM DÜZENİ
#   09:00  SABAH  – kısa kart (IG + FB kare): günün kodu / terimi / bakım ipucu / doğru-yanlış
#   12:30  ANA    – POSTS (IG + FB kare, seçili günlerde LinkedIn 09:00)
#   18:30  STORY  – dikey 1080×1920 (IG + FB story): günün konusuna bağlı anket + link
# ============================================================================

SABAH_LINK = f"{SITE}/?utm_source=instagram&utm_medium=social&utm_campaign=sabah"
STORY_LINK = f"{SITE}/?utm_source=instagram&utm_medium=story&utm_campaign=story"


def _kod(gun, kod, olcu, kullanim, not_, kw, hashtags="genel"):
    return dict(gun=gun, tip="kod", baslik=kod, olcu=olcu, kullanim=kullanim, metin=not_, kw=kw, hashtags=hashtags)


def _terim(gun, terim, metin, kw, hashtags="teknik"):
    return dict(gun=gun, tip="terim", baslik=terim, metin=metin, kw=kw, hashtags=hashtags)


def _ipucu(gun, baslik, metin, kw, hashtags="teknik"):
    return dict(gun=gun, tip="ipucu", baslik=baslik, metin=metin, kw=kw, hashtags=hashtags)


def _soru(gun, soru, cevap, kw, hashtags="teknik"):
    return dict(gun=gun, tip="soru", baslik=soru, metin=cevap, kw=kw, hashtags=hashtags)


SABAH = [
    _kod(1, "6204 ZZ", "20 × 47 × 14", ["Motosiklet tekerlek", "Elektrik motoru", "Redüktör"],
         "En çok sorulan rulman kodu. ZZ: iki tarafı metal kapaklı, ömür boyu yağlı.", "6204 zz rulman, 6204 ölçüleri, 6204 rulman fiyat"),
    _terim(2, "d × D × B", "İç çap × dış çap × kalınlık. Rulmanı tanımlayan üç ölçü. Üzerindeki kod silinmiş olsa bile bu üçünü verirseniz doğru rulmanı buluruz.",
           "rulman ölçüleri, iç çap dış çap kalınlık, rulman ölçüsü nasıl bulunur"),
    _ipucu(3, "KUTUYU KONTROL ET", "Orijinal üründe kutu üzerindeki kod, lot numarası ve rulmanın üstündeki lazer markalama birbirini tutar. Uyuşmuyorsa takma, sor.",
           "orijinal rulman nasıl anlaşılır, sahte rulman, rulman kutusu"),
    _kod(4, "6301 2RS", "12 × 37 × 12", ["Motosiklet ön tekerlek", "Jeneratör", "Küçük redüktör"],
         "6201 ile aynı iç çap, daha kalın bilezik ve büyük bilya: daha fazla yük.", "6301 rulman, 6301 2rs ölçüleri, motosiklet ön tekerlek rulmanı", "moto"),
    _soru(5, "ZZ rulman yeniden greslenebilir.", "YANLIŞ. Metal kapaklar sökülmek için tasarlanmamıştır; rulman fabrikada ömür boyu yetecek gresle gelir. Bittiğinde komple değişir.",
          "zz rulman gresleme, kapaklı rulman yağlama"),
    _kod(6, "608 ZZ", "8 × 22 × 7", ["Kaykay & paten", "3D yazıcı", "Fan & hobi"],
         "Dünyanın en çok üretilen rulmanı. ABEC sınıfı yükseldikçe tolerans daralır.", "608 rulman, 608zz, kaykay rulmanı 608", "kaykay"),
    _terim(7, "ABEC", "Kaykay ve paten dünyasının hassasiyet sınıfı: ABEC 1, 3, 5, 7, 9. Sanayideki karşılığı ISO P0–P2. Yüksek ABEC \"daha hızlı\" değil, \"daha dar toleranslı\" demektir.",
           "abec ne demek, abec 7 rulman, abec 9 rulman", "kaykay"),
    _ipucu(8, "ÇEKİÇLE VURMA", "Rulmanı mile takarken kuvveti yalnızca iç bileziğe, yuvaya takarken yalnızca dış bileziğe uygula. Bilyalar üzerinden geçen darbe yolları çentikler.",
           "rulman montajı nasıl yapılır, rulman takma, rulman montaj hataları"),
    _kod(9, "6304 2RS", "20 × 52 × 15", ["Motosiklet arka tekerlek", "Tarım makinesi", "Kompresör"],
         "6204 ile aynı 20 mm iç çap; dış çap ve kalınlık daha büyük, yük kapasitesi daha yüksek.", "6304 rulman, 6304 2rs, motosiklet arka tekerlek rulmanı", "moto"),
    _soru(10, "6204 ile 6004 aynı mile takılır.", "DOĞRU. İkisinin de iç çapı 20 mm. Fark dış çapta: 6204 → 47 mm, 6004 → 42 mm. Hangisinin gireceğini yuva belirler.",
          "6204 6004 farkı, 6004 rulman ölçüleri"),
    _kod(11, "6001 2RS", "12 × 28 × 8", ["E-scooter tekerlek", "Elektrikli el aleti", "Küçük motor"],
         "Scooter tekerleklerinde en sık değişen kodlardan biri. 2RS: kauçuk keçeli, suya ve toza kapalı.", "6001 rulman, 6001 2rs, scooter tekerlek rulmanı", "scooter"),
    _terim(12, "RADYAL / EKSENEL YÜK", "Radyal yük mile dik, eksenel yük mil boyunca gelir. Sabit bilyalı rulman ikisini de taşır ama eksenelde sınırlıdır; konik makaralı eksenel yükte güçlüdür.",
           "radyal yük eksenel yük, rulman yük tipleri"),
    _ipucu(13, "SICAKLIĞI ÖLÇ", "Rulman yuvası 60 °C'yi geçince ele dokunulmaz olur. Kızılötesi termometre 5 saniyede ölçer; ani sıcaklık artışı arızanın ilk sinyalidir.",
           "rulman sıcaklığı, rulman ısınması nedenleri, rulman arıza belirtisi"),
    _kod(14, "6205 2RS", "25 × 52 × 15", ["Elektrik motoru", "Pompa", "Konveyör"],
         "Sanayide en çok dönen kodlardan biri. Çamaşır makinesi kazanlarında da karşınıza çıkar.", "6205 rulman, 6205 2rs ölçüleri, 6205 fiyat", "sanayi"),
    _kod(15, "6802 ZZ", "15 × 24 × 5", ["Bisiklet göbeği", "Drone & robotik", "İnce mekanizma"],
         "5 mm kalınlık: yer olmayan yerde çözüm. 6800 serisi ince kesit.", "6802 rulman, 6802zz, ince kesit rulman", "bisiklet"),
    _terim(16, "C3", "Standarttan daha büyük iç boşluk. Mil ısınıp genleştiğinde boşluk sıfırlanmasın diye seçilir. Elektrik motorlarında neredeyse standart.",
           "c3 rulman ne demek, c3 boşluk, 6204 c3"),
    _soru(17, "Kutusuz ama parlak rulman orijinaldir.", "ŞÜPHELİ. Parlaklık kaliteyi göstermez. Lazer markalama derinliğine, kutu–lot eşleşmesine ve faturaya bak. Emin değilsen fotoğrafını gönder.",
          "sahte rulman nasıl anlaşılır, orijinal rulman kontrolü"),
    _ipucu(18, "MONTAJ ÖNCESİ TEMİZLİK", "Mili ve yuvayı çapaktan, eski gresten ve talaştan temizle; ince bir yağ filmi sür. Kum tanesi kadar kir rulman ömrünü ciddi kısaltır.",
           "rulman montajı temizlik, rulman ömrü nasıl uzar"),
    _kod(19, "6203 2RS", "17 × 40 × 12", ["Motosiklet", "Kasnak & gergi", "Kompresör"],
         "Küçük motosikletlerde ve kasnak sistemlerinde standart. 6203 ZZ ve 2RS stokta.", "6203 rulman, 6203 2rs, 6203 zz ölçüleri", "moto"),
    _kod(20, "30204", "20 × 47 × 15,25", ["Direksiyon", "Redüktör", "Aks"],
         "Konik makaralı: radyal ve tek yön eksenel yükü birlikte taşır. Çift takılır, ön yükle ayarlanır.", "30204 rulman, 30204 konik rulman ölçüleri", "sanayi"),
    _terim(21, "KONİK MAKARALI", "Makaralar ve yuvarlanma yolları konik. Radyal + tek yönlü eksenel yük. Genellikle karşılıklı çift kullanılır ve montajda ön yük verilir.",
           "konik makaralı rulman nedir, konik rulman kullanım alanları", "sanayi"),
    _soru(22, "Daha fazla gres, daha uzun ömür demektir.", "YANLIŞ. Fazla gres çalkalanır, ısınır ve keçeyi zorlar. Açık rulmanda yuva boş hacminin yaklaşık üçte biri yeterlidir.",
          "rulman gres miktarı, rulman fazla gres, rulman yağlama"),
    _kod(23, "6902 2RS", "15 × 28 × 7", ["Bisiklet göbek", "RC & model", "Robotik"],
         "6900 serisi: 6800'den biraz daha kalın, daha yüklü ince kesit.", "6902 rulman, 6902 2rs, bisiklet göbek rulmanı", "bisiklet"),
    _ipucu(24, "SESİ KAYDET", "Makinenin normal sesini telefonla 10 saniye kaydet; ayda bir aynı noktadan tekrar dinle. Tonun değişmesi arızayı aylar önce haber verir.",
           "rulman sesi nasıl anlaşılır, rulman uğultusu, makine sesi kontrolü"),
    _kod(25, "6206 2RS", "30 × 62 × 16", ["Pompa", "Fan", "Tarım makinesi"],
         "30 mm mil için ilk akla gelen kod. Çamaşır makinesi kazanlarında 6205 ile birlikte kullanılır.", "6206 rulman, 6206 2rs ölçüleri, 6206 fiyat", "sanayi"),
    _terim(26, "ÖN YÜK", "Montajda rulmana bilinçli verilen küçük eksenel sıkılık. Konik rulmanlarda boşluğu sıfırlar; direksiyon ve mil sistemlerinde titreşimi keser.",
           "rulman ön yük nedir, konik rulman ayarı", "sanayi"),
    _kod(27, "6900 ZZ", "10 × 22 × 6", ["Mini scooter", "Drone", "Model & hobi"],
         "10 mm mil, 22 mm yuva. Küçük ama tam bir sabit bilyalı rulman.", "6900 rulman, 6900zz ölçüleri", "scooter"),
    _soru(28, "ZZ, 2RS'ten daha hızlı döner.", "DOĞRU. Metal kapak bileziğe temas etmez, sürtünme düşüktür. 2RS'in kauçuk keçesi sürter ama toz ve suya karşı çok daha iyi korur.",
          "zz 2rs farkı, zz mi 2rs mi, kapaklı rulman"),
    _ipucu(29, "ISITARAK TAK", "Büyük rulmanı 80–100 °C'ye ısıt (indüksiyon ısıtıcı veya yağ banyosu), genleşince mile kaydır. Çekiç değil, ısı.",
           "rulman ısıtarak montaj, indüksiyon ısıtıcı rulman, büyük rulman montajı", "sanayi"),
    _kod(30, "6305 2RS", "25 × 62 × 17", ["Ağır hizmet motor", "Kırıcı", "Tarım"],
         "6205 ile aynı 25 mm mil, çok daha yüksek yük. Darbeli çalışan makinelerin tercihi.", "6305 rulman, 6305 2rs ölçüleri", "sanayi"),
    _terim(31, "RS / 2RS", "Rubber Seal: kauçuk keçe. RS tek taraf, 2RS çift taraf keçeli. Toz ve suya kapalı, gres içeride. Dış ortamda çalışan her rulmanın ilk tercihi.",
           "2rs ne demek, rs rulman, keçeli rulman"),
    _kod(32, "6207 2RS", "35 × 72 × 17", ["Elektrik motoru", "Pompa", "Redüktör"],
         "35 mm mil. Orta güçte elektrik motorlarının ön ve arka yatağında sık karşılaşılır.", "6207 rulman, 6207 2rs, 6207 fiyat", "sanayi"),
    _kod(33, "6202 ZZ", "15 × 35 × 11", ["Fan", "Alternatör", "Küçük motor"],
         "15 mm mil için standart. Fan ve küçük motorların vazgeçilmezi.", "6202 rulman, 6202 zz ölçüleri, 6202 fiyat"),
    _soru(34, "Kaykaydaki 608 ile 3D yazıcıdaki 608 aynıdır.", "DOĞRU. İkisi de 8 × 22 × 7 mm. Fark hassasiyet sınıfı (ABEC) ve kapak tipinde; ölçü her yerde aynıdır.",
          "608 rulman kullanım alanları, 608 ölçüleri", "kaykay"),
    _ipucu(35, "AÇIK RAFTA BEKLETME", "Rulmanı orijinal ambalajında, kuru ve titreşimsiz bir yerde sakla. Açık rafta nem ilk aydan pas başlatır; titreşim duran bilyada iz yapar.",
           "rulman saklama koşulları, rulman depolama, rulman paslanması"),
    _terim(36, "PİTTİNG", "Yuvarlanma yüzeyinde oluşan küçük çukurlar. Yorulma, kir veya aşırı yükün izi. Ses ve titreşimin en yaygın kök nedeni; başladıysa geri dönüşü yok.",
           "pitting nedir, rulman çukurlaşma, rulman arıza analizi"),
    _kod(37, "32005", "25 × 47 × 15", ["Direksiyon", "Aks", "Redüktör"],
         "Konik makaralı, 30205'in ince kesitli kardeşi: aynı mil, daha küçük dış çap.", "32005 rulman, 32005 konik rulman ölçüleri", "sanayi"),
    _kod(38, "6008 2RS", "40 × 68 × 15", ["Pompa", "Mil yatağı", "Takım tezgâhı"],
         "40 mm mil için hafif kesit. Yüksek devir, orta yük.", "6008 rulman, 6008 2rs ölçüleri", "sanayi"),
    _soru(39, "Rulman mile sıkı, yuvaya boş takılır.", "GENELDE DOĞRU. Dönen bilezik sıkı geçme, sabit bilezik hafif geçme. Çoğu uygulamada iç bilezik döner: mile sıkı, yuvaya kaydırmalı.",
          "rulman geçme toleransı, rulman mile nasıl takılır"),
    _kod(40, "NU 204", "20 × 47 × 14", ["Redüktör", "Motor serbest ucu", "Takım tezgâhı"],
         "Silindirik makaralı: 6204 ile aynı ölçü, çok daha yüksek radyal yük. Eksenel yük taşımaz.", "nu 204 rulman, silindirik makaralı rulman ölçüleri", "sanayi"),
    _terim(41, "OYNAK BİLYALI", "1200 / 2200 serisi. Dış bileziğin iç yüzeyi küreseldir; mil eğikliğini (yaklaşık 2–3°) tolere eder. Uzun mil ve konveyörlerde kullanılır.",
           "oynak bilyalı rulman nedir, 1200 serisi rulman", "sanayi"),
    _ipucu(42, "KEÇE YÖNÜNE DİKKAT", "Tek keçeli (RS) rulmanda keçe kirin geldiği tarafa bakmalı. Ters takılan keçe, açık rulman gibi çalışır.",
           "rs rulman keçe yönü, tek keçeli rulman montajı"),
    _kod(43, "6004 2RS", "20 × 42 × 12", ["E-scooter tekerlek", "Çim biçme", "Küçük motor"],
         "20 mm mil, 42 mm yuva. Scooter ve bahçe makinelerinde 6204'ün hafif kesitli alternatifi.", "6004 rulman, 6004 2rs ölçüleri, scooter rulmanı", "scooter"),
    _soru(44, "Rulman kodu her markada aynı ölçüyü verir.", "DOĞRU. 6204 hangi markadan olsun 20 × 47 × 14 mm'dir (ISO 15). Markalar arasındaki fark ölçüde değil; malzeme, tolerans ve ömürdedir.",
          "rulman kodları standart, rulman kodu ölçü"),
    _kod(45, "6010 2RS", "50 × 80 × 16", ["Pompa", "Mil yatağı", "Konveyör"],
         "50 mm mil için hafif kesit. Büyük ölçülerde stok bilgisini siteden anlık görebilirsiniz.", "6010 rulman, 6010 2rs ölçüleri", "sanayi"),
    _ipucu(46, "SÖKTÜĞÜNÜ TEKRAR TAKMA", "Çektirmeyle çıkan rulmanın bilezikleri gerilir, bilya yolları iz alır. Ekonomik görünür; erken biter ve mili de götürür.",
           "sökülen rulman tekrar kullanılır mı, rulman sökme"),
    _terim(47, "YATAKLI RULMAN", "Rulman ve dökme yuva tek parça: UCP ayaklı, UCF kare flanşlı, UCFL oval flanşlı. Setuskurla mile bağlanır; konveyör ve tarımın standart yatağı.",
           "yataklı rulman nedir, ucp ucf ucfl farkı", "sanayi"),
    _kod(48, "UCP 205", "Mil çapı 25", ["Konveyör", "Tarım makinesi", "Tekstil"],
         "Ayaklı yataklı ünite. İçindeki rulman UC 205 (25 × 52 × 34,1). Yuva ve rulman ayrı ayrı da stokta.", "ucp 205 rulman, ucp 205 yatak, uc 205", "sanayi"),
    _soru(49, "Makaralı rulman, bilyalıdan daha fazla yük taşır.", "DOĞRU. Makaranın çizgi teması bilyanın nokta temasından daha geniş yüzeye yayılır. Bilyalı ise daha hızlı döner ve daha az ısınır.",
          "bilyalı makaralı rulman farkı, hangi rulman daha çok yük taşır", "sanayi"),
    _kod(50, "1204", "20 × 47 × 14", ["Konveyör", "Tarım", "Fan"],
         "Oynak bilyalı: 6204 ölçüsünde, mil eğikliğini tolere eder. Uzun ve esnek millerde.", "1204 rulman, 1204 oynak bilyalı ölçüleri", "sanayi"),
    _ipucu(51, "AYDA 3 DAKİKA", "Ses, sıcaklık, titreşim: her rulman noktasına ayda bir 3 dakika ayır. Bu küçük alışkanlık yıllık plansız duruşu önler.",
           "kestirimci bakım rulman, rulman kontrol listesi"),
    _kod(52, "6300 2RS", "10 × 35 × 11", ["Küçük redüktör", "Motosiklet mekanizma", "Elektrikli alet"],
         "10 mm mil için en yüklü sabit bilyalı seçenek. 6000 ve 6200'den kalın ve güçlü.", "6300 rulman, 6300 2rs ölçüleri"),
    _terim(53, "LAZER MARKALAMA", "Orijinal rulmanda kod, marka ve menşei lazerle kazınır: eşit derinlik, net kenar. Silik, kaymış veya yalnızca boya baskılı yazı şüphe nedenidir.",
           "rulman lazer markalama, orijinal rulman işareti"),
    _kod(54, "6308 2RS", "40 × 90 × 23", ["Kırıcı", "Değirmen", "Ağır motor"],
         "40 mm mil, ağır hizmet. Darbeli yük altında çalışan makinelerin tercihi.", "6308 rulman, 6308 2rs ölçüleri, 6308 fiyat", "sanayi"),
    _ipucu(55, "MOTOR RULMANINDA C3", "Elektrik motorları çalışırken ısınır; mil genleşir. Bu yüzden motor rulmanlarında çoğunlukla C3 boşluk kullanılır. Etiketteki koda bak, aynısını iste.",
           "elektrik motoru rulmanı c3, motor rulmanı seçimi", "sanayi"),
    _soru(56, "Ses yoksa rulman sağlamdır.", "YANLIŞ. Pitting başlangıcı sessizdir. Titreşim ve sıcaklık artışı sesten aylar önce sinyal verir; sadece kulağa güvenme.",
          "rulman arızası belirtileri, sessiz rulman arızası"),
    _kod(57, "6209 2RS", "45 × 85 × 19", ["Pompa", "Fan", "Redüktör"],
         "45 mm mil. Yıl sonu duruşu için kritik listenizde varsa şimdiden ayırtın.", "6209 rulman, 6209 2rs ölçüleri", "sanayi"),
    _terim(58, "NLGI 2", "Gresin kıvam sınıfı. Rulmanlarda en yaygını NLGI 2. NLGI 1 daha akışkan (soğuk ortam, merkezi yağlama), NLGI 3 daha katı (dik mil, yüksek sıcaklık).",
           "nlgi 2 gres, rulman gresi seçimi, nlgi ne demek", "sanayi"),
    _kod(59, "UCF 206", "Mil çapı 30", ["Duvar & plaka montajı", "Konveyör", "Paketleme"],
         "Kare flanşlı yataklı ünite. İç rulmanı UC 206. Dört cıvatayla plakaya bağlanır.", "ucf 206 rulman, ucf 206 yatak, uc 206", "sanayi"),
    _ipucu(60, "ÖLÇÜNÜ YAZ, GERİSİNİ BIRAK", "İç çap, dış çap, kalınlık. Kodu bilmesen de bu üç ölçüyle rulmanını buluruz. DM'den yaz, aynı gün cevap.",
           "ölçüye göre rulman bulma, rulman kodu bulma", "genel"),
]


def sabah_ig(s):
    """Sabah kartının IG/FB metni – alanlardan üretilir."""
    if s["tip"] == "kod":
        return (f"Günün kodu: {s['baslik']}\n"
                f"Ölçü: {s['olcu']} mm (iç çap × dış çap × kalınlık)\n"
                f"Kullanım: {', '.join(s['kullanim'])}\n\n{s['metin']}\n\n"
                f"Stokta. Kodu yaz, aynı gün kargolayalım: yamansarulman.com")
    if s["tip"] == "terim":
        return f"Günün terimi: {s['baslik']}\n\n{s['metin']}\n\nSorunuz varsa yorumlara yazın, cevaplıyoruz."
    if s["tip"] == "ipucu":
        return f"Bakım ipucu: {s['baslik'].capitalize()}\n\n{s['metin']}\n\nKaydet; bakım günü lazım olur."
    return f"Doğru mu, yanlış mı?\n\n\"{s['baslik']}\"\n\nCevap: {s['metin']}"


def sabah_alt_text(s):
    etiket = {"kod": "Günün kodu kartı", "terim": "Günün terimi kartı", "ipucu": "Bakım ipucu kartı", "soru": "Doğru mu yanlış mı kartı"}[s["tip"]]
    b = s["baslik"]
    return f"{etiket}: {b}" + (f" rulman, {s['olcu']} mm" if s["tip"] == "kod" else "")


# ---------------------------------------------------------------------------
# AKŞAM STORY (18:30) – günün ana gönderisine bağlı anket. soru=None ise sadece mesaj + link.
#   (gun, soru, seçenek A, seçenek B)  veya  (gun, None, mesaj, None)

_S = [
    (1, "Rulmanı nereden alıyorsun?", "Sanayi çarşısı", "Online"),
    (2, "Elinden en çok hangi seri geçiyor?", "6200", "6300"),
    (3, "Senin tercihin?", "ZZ", "2RS"),
    (4, "Tekerlek rulmanını en son ne zaman değiştirdin?", "1 yıl içinde", "Hatırlamıyorum"),
    (5, "Rulmanda önceliğin?", "Marka", "Fiyat"),
    (6, "6204-2RS C3 kodunu okuyabilir misin?", "Evet", "Öğrenmek isterim"),
    (7, "Makinende garip bir ses var mı?", "Var", "Yok"),
    (8, "Scooter'ın markası?", "Xiaomi / Segway", "Diğer"),
    (9, "6300 serisini nerede kullanıyorsun?", "Motosiklet", "Sanayi"),
    (10, "C3 boşluk ne demek biliyor muydun?", "Biliyordum", "Yeni öğrendim"),
    (11, "Rulmanın bittiğini ilk nasıl anlarsın?", "Ses", "Titreşim"),
    (12, "Acil rulmanı kaç günde alabiliyorsun?", "1 gün", "3+ gün"),
    (13, "Elinin altında kumpas var mı?", "Var", "Yok"),
    (14, "2RS rulmanı hiç gresledin mi?", "Evet", "Hayır"),
    (15, "Göbek rulmanını kim değiştiriyor?", "Kendim", "Servis"),
    (16, "İnce kesit rulman kullanıyor musun?", "Evet", "Hayır"),
    (17, "Kaç tedarikçiden alım yapıyorsun?", "1–2", "3+"),
    (18, "Rulmanı hiç çekiçle taktın mı?", "Evet 🙈", "Hayır"),
    (19, "Yamansa marka setleri denedin mi?", "Evet", "Henüz"),
    (20, "Motorun?", "Honda / Yamaha", "Diğer"),
    (21, "Katılıyor musun?", "Evet", "Kesinlikle"),
    (22, "İşinde hangisi daha çok?", "Konik", "Silindirik"),
    (23, "6800 / 6900 nerede karşına çıkıyor?", "Bisiklet", "Drone / robotik"),
    (24, "Stok bilgisine nasıl bakıyorsun?", "Siteden", "Telefonla"),
    (25, "Kumpasla ölçüm yapabiliyor musun?", "Evet", "Öğrenmek isterim"),
    (26, "Senin makinende hangisi?", "6204", "6304"),
    (27, "Bize en çok ne soruyorsun?", "Fiyat", "Muadil"),
    (28, "Ön + arka set ister misin?", "Evet", "Sadece ön"),
    (29, "Yamansa'yı ne zamandır tanıyorsun?", "5+ yıl", "Yeni tanıştım"),
    (30, "Sitedeki ölçü filtresini denedin mi?", "Evet", "Şimdi deneyeceğim"),
    (31, "Kapak kodlarını karıştırıyor musun?", "Evet", "Hayır"),
    (32, "Büyük ölçüde en çok?", "6206–6207", "6208+"),
    (33, "Çamaşır makinesinde rulman değiştirdin mi?", "Evet", "Hayır"),
    (34, "608'i nerede kullanıyorsun?", "Kaykay / paten", "3D yazıcı / hobi"),
    (35, "Katılıyor musun?", "Evet", "Kesinlikle"),
    (36, "Sende rulman en çok neden bitiyor?", "Kir / su", "Montaj hatası"),
    (37, "Konik rulman çiftini kim ayarlıyor?", "Kendim", "Servis"),
    (38, "Kritik yedek listen var mı?", "Var", "Yok"),
    (39, None, "Nice yüzyıllara. Yaşasın Cumhuriyet!", None),
    (40, "Uygulaman için hangisi?", "Bilyalı", "Makaralı"),
    (41, "Direksiyonda boşluk hissediyor musun?", "Evet", "Hayır"),
    (42, "Katılıyor musun?", "Evet", "Kesinlikle"),
    (43, "NU ile NJ farkını biliyor muydun?", "Biliyordum", "Yeni öğrendim"),
    (44, "Kodun ek harflerine bakar mısın?", "Bakarım", "Sadece ana kod"),
    (45, "Cari hesapla çalışmak ister misin?", "Evet", "Bilgi istiyorum"),
    (46, "Rulmanı nasıl söküyorsun?", "Çektirme", "Çekiç / keski"),
    (47, "Şehrinde paylaşımlı scooter var mı?", "Var", "Yok"),
    (48, "Bunlardan birini biliyor muydun?", "Evet", "Hayır"),
    (49, "Katılıyor musun?", "Evet", "Kesinlikle"),
    (50, "Oynak rulman kullandın mı?", "Evet", "Hayır"),
    (51, None, "10 Kasım 09.05 — Ulu Önder Atatürk'ü özlemle anıyoruz.", None),
    (52, "Senin uygulaman?", "Açık", "Kapaklı"),
    (53, "Sahte rulmanla karşılaştın mı?", "Evet", "Hayır"),
    (54, "Ağır hizmette kodun?", "6306–6308", "6309+"),
    (55, "Motor bakımı / sarımı yapıyor musun?", "Evet", "Hayır"),
    (56, "Katılıyor musun?", "Evet", "Kesinlikle"),
    (57, "Yıl sonu duruş planın hazır mı?", "Hazır", "Henüz değil"),
    (58, "Gresi neye göre seçiyorsun?", "Katalog", "Alışkanlık"),
    (59, "Sende hangisi var?", "UCP", "UCF / UCFL"),
    (60, None, "Sorunu DM'den yaz, aynı gün cevaplıyoruz.", None),
]

AKSAM = [dict(gun=g, soru=q, a=a, b=b) for g, q, a, b in _S]

POST_BY_GUN = {p["gun"]: p for p in POSTS}
